// This is a personal academic project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com

//This Is A Beast Engine File Which Has The License Apache 2.0

#include <iostream>
#include "RenderText.h"
#include "Init.h"
#include "ErrorReporter.h"

int RenderText::Init()
{
	if (TTF_Init() != 0)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

void RenderText::Load()
{
	M_CalibriFont = TTF_OpenFont("Fonts/calibri.ttf", 82);
	M_AGENCYB = TTF_OpenFont("Fonts/AGENCYB.ttf", 82);
	M_AGENCYR = TTF_OpenFont("Fonts/AGENCYR.ttf", 82);
	M_ALGER = TTF_OpenFont("Fonts/ALGER.ttf", 82);
	M_ANTQUAB = TTF_OpenFont("Fonts/ANTQUAB.ttf", 82);
	M_ANTQUABI = TTF_OpenFont("Fonts/ANTQUABI.ttf", 82);
	M_ANTQUAI = TTF_OpenFont("Fonts/ANTQUAI.ttf", 82);
	M_arial = TTF_OpenFont("Fonts/arial.ttf", 82);
	M_arialbd = TTF_OpenFont("Fonts/arialbd.ttf", 82);
	M_arialbi = TTF_OpenFont("Fonts/arialbi.ttf", 82);
	M_ariali = TTF_OpenFont("Fonts/ariali.ttf", 82);
	M_ARIALN = TTF_OpenFont("Fonts/ARIALN.ttf", 82);
	M_ARIALNB = TTF_OpenFont("Fonts/ARIALNB.ttf", 82);
	M_ARIALNBI = TTF_OpenFont("Fonts/ARIALNBI.ttf", 82);
	M_ARIALNI = TTF_OpenFont("Fonts/ARIALNI.ttf", 82);
	M_ariblk = TTF_OpenFont("Fonts/ariblk.ttf", 82);
	M_ARLRDBD = TTF_OpenFont("Fonts/ARLRDBD.ttf", 82);
	M_bahnschrift = TTF_OpenFont("Fonts/bahnschrift.ttf", 82);
	M_BASKVILL = TTF_OpenFont("Fonts/BASKVILL.ttf", 82);
	M_BAUHS93 = TTF_OpenFont("Fonts/BAUHS93.ttf", 82);
	M_BELL = TTF_OpenFont("Fonts/BELL.ttf", 82);
	M_BELLB = TTF_OpenFont("Fonts/BELLB.ttf", 82);
	M_BELLI = TTF_OpenFont("Fonts/BELLI.ttf", 82);
	M_BERNHC = TTF_OpenFont("Fonts/BERNHC.ttf", 82);
	M_BKANT = TTF_OpenFont("Fonts/BKANT.ttf", 82);
	M_BOD_B = TTF_OpenFont("Fonts/BOD_B.ttf", 82);
	M_BOD_BI = TTF_OpenFont("Fonts/BOD_BI.ttf", 82);
	M_BOD_BLAI = TTF_OpenFont("Fonts/BOD_BLAI.ttf", 82);
	M_BOD_BLAR = TTF_OpenFont("Fonts/BOD_BLAR.ttf", 82);
	M_BOD_CB = TTF_OpenFont("Fonts/BOD_CB.ttf", 82);
	M_BOD_CBI = TTF_OpenFont("Fonts/BOD_CBI.ttf", 82);
	M_BOD_CI = TTF_OpenFont("Fonts/BOD_CI.ttf", 82);
	M_BOD_CR = TTF_OpenFont("Fonts/BOD_CR.ttf", 82);
	M_BOD_I = TTF_OpenFont("Fonts/BOD_I.ttf", 82);
	M_BOD_PSTC = TTF_OpenFont("Fonts/BOD_PSTC.ttf", 82);
	M_BOD_R = TTF_OpenFont("Fonts/BOD_R.ttf", 82);
	M_BOOKOS = TTF_OpenFont("Fonts/BOOKOS.ttf", 82);
	M_BOOKOSB = TTF_OpenFont("Fonts/BOOKOSB.ttf", 82);
	M_BOOKOSBI = TTF_OpenFont("Fonts/BOOKOSBI.ttf", 82);
	M_BOOKOSI = TTF_OpenFont("Fonts/BOOKOSI.ttf", 82);
	M_BRADHITC = TTF_OpenFont("Fonts/BRADHITC.ttf", 82);
	M_BRITANIC = TTF_OpenFont("Fonts/BRITANIC.ttf", 82);
	M_BRLNSB = TTF_OpenFont("Fonts/BRLNSB.ttf", 82);
	M_BRLNSDB = TTF_OpenFont("Fonts/BRLNSDB.ttf", 82);
	M_BRLNSR = TTF_OpenFont("Fonts/BRLNSR.ttf", 82);
	M_BROADW = TTF_OpenFont("Fonts/BROADW.ttf", 82);
	M_BRUSHSCI = TTF_OpenFont("Fonts/BRUSHSCI.ttf", 82);
	M_BSSYM7 = TTF_OpenFont("Fonts/BSSYM7.ttf", 82);
	M_calibrib = TTF_OpenFont("Fonts/calibrib.ttf", 82);
	M_calibrii = TTF_OpenFont("Fonts/calibrii.ttf", 82);
	M_calibril = TTF_OpenFont("Fonts/calibril.ttf", 82);
	M_calibrili = TTF_OpenFont("Fonts/calibrili.ttf", 82);
	M_calibriz = TTF_OpenFont("Fonts/calibriz.ttf", 82);
	M_CALIFB = TTF_OpenFont("Fonts/CALIFB.ttf", 82);
	M_CALIFI = TTF_OpenFont("Fonts/CALIFI.ttf", 82);
	M_CALIFR = TTF_OpenFont("Fonts/CALIFR.ttf", 82);
	M_CALIST = TTF_OpenFont("Fonts/CALIST.ttf", 82);
	M_CALISTB = TTF_OpenFont("Fonts/CALISTB.ttf", 82);
	M_CALISTBI = TTF_OpenFont("Fonts/CALISTBI.ttf", 82);
	M_CALISTI = TTF_OpenFont("Fonts/CALISTI.ttf", 82);
	M_cambriab = TTF_OpenFont("Fonts/cambriab.ttf", 82);
	M_cambriai = TTF_OpenFont("Fonts/cambriai.ttf", 82);
	M_cambriaz = TTF_OpenFont("Fonts/cambriaz.ttf", 82);
	M_Candara = TTF_OpenFont("Fonts/Candara.ttf", 82);
	M_Candarab = TTF_OpenFont("Fonts/Candarab.ttf", 82);
	M_Candarai = TTF_OpenFont("Fonts/Candarai.ttf", 82);
	M_Candaral = TTF_OpenFont("Fonts/Candaral.ttf", 82);
	M_Candarali = TTF_OpenFont("Fonts/Candarali.ttf", 82);
	M_Candaraz = TTF_OpenFont("Fonts/Candaraz.ttf", 82);
	M_CASTELAR = TTF_OpenFont("Fonts/CASTELAR.ttf", 82);
	M_CENSCBK = TTF_OpenFont("Fonts/CENSCBK.ttf", 82);
	M_CENTAUR = TTF_OpenFont("Fonts/CENTAUR.ttf", 82);
	M_CENTURY = TTF_OpenFont("Fonts/CENTURY.ttf", 82);
	M_CHILLER = TTF_OpenFont("Fonts/CHILLER.ttf", 82);
	M_COLONNA = TTF_OpenFont("Fonts/COLONNA.ttf", 82);
	M_comic = TTF_OpenFont("Fonts/comic.ttf", 82);
	M_comicbd = TTF_OpenFont("Fonts/comicbd.ttf", 82);
	M_comici = TTF_OpenFont("Fonts/comici.ttf", 82);
	M_comicz = TTF_OpenFont("Fonts/comicz.ttf", 82);
	M_consola = TTF_OpenFont("Fonts/consola.ttf", 82);
	M_consolab = TTF_OpenFont("Fonts/consolab.ttf", 82);
	M_consolai = TTF_OpenFont("Fonts/consolai.ttf", 82);
	M_consolaz = TTF_OpenFont("Fonts/consolaz.ttf", 82);
	M_constan = TTF_OpenFont("Fonts/constan.ttf", 82);
	M_constanb = TTF_OpenFont("Fonts/constanb.ttf", 82);
	M_constani = TTF_OpenFont("Fonts/constani.ttf", 82);
	M_constanz = TTF_OpenFont("Fonts/constanz.ttf", 82);
	M_COOPBL = TTF_OpenFont("Fonts/COOPBL.ttf", 82);
	M_COPRGTB = TTF_OpenFont("Fonts/COPRGTB.ttf", 82);
	M_COPRGTL = TTF_OpenFont("Fonts/COPRGTL.ttf", 82);
	M_corbel = TTF_OpenFont("Fonts/corbel.ttf", 82);
	M_corbelb = TTF_OpenFont("Fonts/corbelb.ttf", 82);
	M_corbeli = TTF_OpenFont("Fonts/corbeli.ttf", 82);
	M_corbell = TTF_OpenFont("Fonts/corbell.ttf", 82);
	M_corbelli = TTF_OpenFont("Fonts/corbelli.ttf", 82);
	M_corbelz = TTF_OpenFont("Fonts/corbelz.ttf", 82);
	M_cour = TTF_OpenFont("Fonts/cour.ttf", 82);
	M_courbd = TTF_OpenFont("Fonts/courbd.ttf", 82);
	M_courbi = TTF_OpenFont("Fonts/courbi.ttf", 82);
	M_couri = TTF_OpenFont("Fonts/couri.ttf", 82);
	M_CURLZ___ = TTF_OpenFont("Fonts/CURLZ___.ttf", 82);
	M_ebrima = TTF_OpenFont("Fonts/ebrima.ttf", 82);
	M_ebrimabd = TTF_OpenFont("Fonts/ebrimabd.ttf", 82);
	M_ELEPHNT = TTF_OpenFont("Fonts/ELEPHNT.ttf", 82);
	M_ELEPHNTI = TTF_OpenFont("Fonts/ELEPHNTI.ttf", 82);
	M_ENGR = TTF_OpenFont("Fonts/ENGR.ttf", 82);
	M_ERASBD = TTF_OpenFont("Fonts/ERASBD.ttf", 82);
	M_ERASDEMI = TTF_OpenFont("Fonts/ERASDEMI.ttf", 82);
	M_ERASLGHT = TTF_OpenFont("Fonts/ERASLGHT.ttf", 82);
	M_ERASMD = TTF_OpenFont("Fonts/ERASMD.ttf", 82);
	M_FELIXTI = TTF_OpenFont("Fonts/FELIXTI.ttf", 82);
	M_FORTE = TTF_OpenFont("Fonts/FORTE.ttf", 82);
	M_FRABK = TTF_OpenFont("Fonts/FRABK.ttf", 82);
	M_FRABKIT = TTF_OpenFont("Fonts/FRABKIT.ttf", 82);
	M_FRADM = TTF_OpenFont("Fonts/FRADM.ttf", 82);
	M_FRADMCN = TTF_OpenFont("Fonts/FRADMCN.ttf", 82);
	M_FRADMIT = TTF_OpenFont("Fonts/FRADMIT.ttf", 82);
	M_FRAHV = TTF_OpenFont("Fonts/FRAHV.ttf", 82);
	M_FRAHVIT = TTF_OpenFont("Fonts/FRAHVIT.ttf", 82);
	M_framd = TTF_OpenFont("Fonts/framd.ttf", 82);
	M_FRAMDCN = TTF_OpenFont("Fonts/FRAMDCN.ttf", 82);
	M_framdit = TTF_OpenFont("Fonts/framdit.ttf", 82);
	M_FREESCPT = TTF_OpenFont("Fonts/FREESCPT.ttf", 82);
	M_FRSCRIPT = TTF_OpenFont("Fonts/FRSCRIPT.ttf", 82);
	M_FTLTLT = TTF_OpenFont("Fonts/FTLTLT.ttf", 82);
	M_Gabriola = TTF_OpenFont("Fonts/Gabriola.ttf", 82);
	M_gadugi = TTF_OpenFont("Fonts/gadugi.ttf", 82);
	M_gadugib = TTF_OpenFont("Fonts/gadugib.ttf", 82);
	M_GARA = TTF_OpenFont("Fonts/GARA.ttf", 82);
	M_GARABD = TTF_OpenFont("Fonts/GARABD.ttf", 82);
	M_GARAIT = TTF_OpenFont("Fonts/GARAIT.ttf", 82);
	M_georgia = TTF_OpenFont("Fonts/georgia.ttf", 82);
	M_georgiab = TTF_OpenFont("Fonts/georgiab.ttf", 82);
	M_georgiai = TTF_OpenFont("Fonts/georgiai.ttf", 82);
	M_georgiaz = TTF_OpenFont("Fonts/georgiaz.ttf", 82);
	M_GIGI = TTF_OpenFont("Fonts/GIGI.ttf", 82);
	M_GIL_____ = TTF_OpenFont("Fonts/GIL_____.ttf", 82);
	M_GILB____ = TTF_OpenFont("Fonts/GILB____.ttf", 82);
	M_GILBI___ = TTF_OpenFont("Fonts/GILBI___.ttf", 82);
	M_GILC____ = TTF_OpenFont("Fonts/GILC____.ttf", 82);
	M_GILI____ = TTF_OpenFont("Fonts/GILI____.ttf", 82);
	M_GILLUBCD = TTF_OpenFont("Fonts/GILLUBCD.ttf", 82);
	M_GILSANUB = TTF_OpenFont("Fonts/GILSANUB.ttf", 82);
	M_GLECB = TTF_OpenFont("Fonts/GLECB.ttf", 82);
	M_GLSNECB = TTF_OpenFont("Fonts/GLSNECB.ttf", 82);
	M_GOTHIC = TTF_OpenFont("Fonts/GOTHIC.ttf", 82);
	M_GOTHICB = TTF_OpenFont("Fonts/GOTHICB.ttf", 82);
	M_GOTHICBI = TTF_OpenFont("Fonts/GOTHICBI.ttf", 82);
	M_GOTHICI = TTF_OpenFont("Fonts/GOTHICI.ttf", 82);
	M_GOUDOS = TTF_OpenFont("Fonts/GOUDOS.ttf", 82);
	M_GOUDOSB = TTF_OpenFont("Fonts/GOUDOSB.ttf", 82);
	M_GOUDOSI = TTF_OpenFont("Fonts/GOUDOSI.ttf", 82);
	M_GOUDYSTO = TTF_OpenFont("Fonts/GOUDYSTO.ttf", 82);
	M_HARLOWSI = TTF_OpenFont("Fonts/HARLOWSI.ttf", 82);
	M_HARNGTON = TTF_OpenFont("Fonts/HARNGTON.ttf", 82);
	M_HATTEN = TTF_OpenFont("Fonts/HATTEN.ttf", 82);
	M_holomdl2 = TTF_OpenFont("Fonts/holomdl2.ttf", 82);
	M_HPSimplified = TTF_OpenFont("Fonts/HPSimplified.ttf", 82);
	M_HPSimplified_BdIt = TTF_OpenFont("Fonts/HPSimplified_BdIt.ttf", 82);
	M_HPSimplified_It = TTF_OpenFont("Fonts/HPSimplified_It.ttf", 82);
	M_HPSimplified_Lt = TTF_OpenFont("Fonts/HPSimplified_Lt.ttf", 82);
	M_HPSimplified_LtIt = TTF_OpenFont("Fonts/HPSimplified_LtIt.ttf", 82);
	M_HPSimplified_Rg = TTF_OpenFont("Fonts/HPSimplified_Rg.ttf", 82);
	//
	M_hpsimplifiedjpan_light = TTF_OpenFont("Fonts/hpsimplifiedjpan_light.ttf", 82);
	//
	M_hpsimplifiedjpan_regular = TTF_OpenFont("Fonts/hpsimplifiedjpan_regular.ttf", 82);
	M_HTOWERT = TTF_OpenFont("Fonts/HTOWERT.ttf", 82);
	M_HTOWERTI = TTF_OpenFont("Fonts/HTOWERTI.ttf", 82);
	M_impact = TTF_OpenFont("Fonts/impact.ttf", 82);
	M_IMPRISHA = TTF_OpenFont("Fonts/IMPRISHA.ttf", 82);
	M_INFROMAN = TTF_OpenFont("Fonts/INFROMAN.ttf", 82);
	M_Inkfree = TTF_OpenFont("Fonts/Inkfree.ttf", 82);
	M_ITCBLKAD = TTF_OpenFont("Fonts/ITCBLKAD.ttf", 82);
	M_ITCEDSCR = TTF_OpenFont("Fonts/ITCEDSCR.ttf", 82);
	M_ITCKRIST = TTF_OpenFont("Fonts/ITCKRIST.ttf", 82);
	M_javatext = TTF_OpenFont("Fonts/javatext.ttf", 82);
	M_JOKERMAN = TTF_OpenFont("Fonts/JOKERMAN.ttf", 82);
	M_JUICE___ = TTF_OpenFont("Fonts/JUICE___.ttf", 82);
	M_KUNSTLER = TTF_OpenFont("Fonts/KUNSTLER.ttf", 82);
	M_l_10646 = TTF_OpenFont("Fonts/l_10646.ttf", 82);
	M_LATINWD = TTF_OpenFont("Fonts/LATINWD.ttf", 82);
	M_LBRITE = TTF_OpenFont("Fonts/LBRITE.ttf", 82);
	M_LBRITED = TTF_OpenFont("Fonts/LBRITED.ttf", 82);
	M_LBRITEDI = TTF_OpenFont("Fonts/LBRITEDI.ttf", 82);
	M_LBRITEI = TTF_OpenFont("Fonts/LBRITEI.ttf", 82);
	M_LCALLIG = TTF_OpenFont("Fonts/LCALLIG.ttf", 82);
	M_LFAX = TTF_OpenFont("Fonts/LFAX.ttf", 82);
	M_LFAXD = TTF_OpenFont("Fonts/LFAXD.ttf", 82);
	M_LFAXDI = TTF_OpenFont("Fonts/LFAXDI.ttf", 82);
	M_LFAXI = TTF_OpenFont("Fonts/LFAXI.ttf", 82);
	M_LHANDW = TTF_OpenFont("Fonts/LHANDW.ttf", 82);
	M_LSANS = TTF_OpenFont("Fonts/LSANS.ttf", 82);
	M_LSANSD = TTF_OpenFont("Fonts/LSANSD.ttf", 82);
	M_LSANSDI = TTF_OpenFont("Fonts/LSANSDI.ttf", 82);
	M_LSANSI = TTF_OpenFont("Fonts/LSANSI.ttf", 82);
	M_LTYPE = TTF_OpenFont("Fonts/LTYPE.ttf", 82);
	M_LTYPEB = TTF_OpenFont("Fonts/LTYPEB.ttf", 82);
	M_LTYPEBO = TTF_OpenFont("Fonts/LTYPEBO.ttf", 82);
	M_LTYPEO = TTF_OpenFont("Fonts/LTYPEO.ttf", 82);
	M_lucon = TTF_OpenFont("Fonts/lucon.ttf", 82);
	M_MAGNETOB = TTF_OpenFont("Fonts/MAGNETOB.ttf", 82);
	M_MAIAN = TTF_OpenFont("Fonts/MAIAN.ttf", 82);
	M_MATURASC = TTF_OpenFont("Fonts/MATURASC.ttf", 82);
	M_MISTRAL = TTF_OpenFont("Fonts/MISTRAL.ttf", 82);
	M_mmrtext = TTF_OpenFont("Fonts/mmrtext.ttf", 82);
	M_MOD20 = TTF_OpenFont("Fonts/MOD20.ttf", 82);
	M_MTCORSVA = TTF_OpenFont("Fonts/MTCORSVA.ttf", 82);
	M_NIAGENG = TTF_OpenFont("Fonts/NIAGENG.ttf", 82);
	M_NIAGSOL = TTF_OpenFont("Fonts/NIAGSOL.ttf", 82);
	M_OCRAEXT = TTF_OpenFont("Fonts/OCRAEXT.ttf", 82);
	M_OLDENGL = TTF_OpenFont("Fonts/OLDENGL.ttf", 82);
	M_ONYX = TTF_OpenFont("Fonts/ONYX.ttf", 82);
	M_pala = TTF_OpenFont("Fonts/pala.ttf", 82);
	M_palab = TTF_OpenFont("Fonts/palab.ttf", 82);
	M_palabi = TTF_OpenFont("Fonts/palabi.ttf", 82);
	M_palai = TTF_OpenFont("Fonts/palai.ttf", 82);
	M_PALSCRI = TTF_OpenFont("Fonts/PALSCRI.ttf", 82);
	M_PAPYRUS = TTF_OpenFont("Fonts/PAPYRUS.ttf", 82);
	M_PARCHM = TTF_OpenFont("Fonts/PARCHM.ttf", 82);
	M_PER_____ = TTF_OpenFont("Fonts/PER_____.ttf", 82);
	M_PERB____ = TTF_OpenFont("Fonts/PERB____.ttf", 82);
	M_PERBI___ = TTF_OpenFont("Fonts/PERBI___.ttf", 82);
	M_PERI____ = TTF_OpenFont("Fonts/PERI____.ttf", 82);
	M_PERTIBD = TTF_OpenFont("Fonts/PERTIBD.ttf", 82);
	M_PERTILI = TTF_OpenFont("Fonts/PERTILI.ttf", 82);
	M_PLAYBILL = TTF_OpenFont("Fonts/PLAYBILL.ttf", 82);
	M_POORICH = TTF_OpenFont("Fonts/POORICH.ttf", 82);
	M_PRISTINA = TTF_OpenFont("Fonts/PRISTINA.ttf", 82);
	M_RAGE = TTF_OpenFont("Fonts/RAGE.ttf", 82);
	M_RAVIE = TTF_OpenFont("Fonts/RAVIE.ttf", 82);
	M_REFSAN = TTF_OpenFont("Fonts/REFSAN.ttf", 82);
	M_REFSPCL = TTF_OpenFont("Fonts/REFSPCL.ttf", 82);
	M_ROCC____ = TTF_OpenFont("Fonts/ROCC____.ttf", 82);
	M_ROCCB___ = TTF_OpenFont("Fonts/ROCCB___.ttf", 82);
	M_ROCK = TTF_OpenFont("Fonts/ROCK.ttf", 82);
	M_ROCKB = TTF_OpenFont("Fonts/ROCKB.ttf", 82);
	M_ROCKBI = TTF_OpenFont("Fonts/ROCKBI.ttf", 82);
	M_ROCKEB = TTF_OpenFont("Fonts/ROCKEB.ttf", 82);
	M_ROCKI = TTF_OpenFont("Fonts/ROCKI.ttf", 82);
	M_SCHLBKB = TTF_OpenFont("Fonts/SCHLBKB.ttf", 82);
	M_SCHLBKBI = TTF_OpenFont("Fonts/SCHLBKBI.ttf", 82);
	M_SCHLBKI = TTF_OpenFont("Fonts/SCHLBKI.ttf", 82);
	M_SCRIPTBL = TTF_OpenFont("Fonts/SCRIPTBL.ttf", 82);
	M_segmdl2 = TTF_OpenFont("Fonts/segmdl2.ttf", 82);
	M_segoepr = TTF_OpenFont("Fonts/segoepr.ttf", 82);
	M_segoeprb = TTF_OpenFont("Fonts/segoeprb.ttf", 82);
	M_segoesc = TTF_OpenFont("Fonts/segoesc.ttf", 82);
	M_segoescb = TTF_OpenFont("Fonts/segoescb.ttf", 82);
	M_segoeui = TTF_OpenFont("Fonts/segoeui.ttf", 82);
	M_segoeuib = TTF_OpenFont("Fonts/segoeuib.ttf", 82);
	M_segoeuii = TTF_OpenFont("Fonts/segoeuii.ttf", 82);
	M_segoeuil = TTF_OpenFont("Fonts/segoeuil.ttf", 82);
	M_segoeuisl = TTF_OpenFont("Fonts/segoeuisl.ttf", 82);
	M_segoeuiz = TTF_OpenFont("Fonts/segoeuiz.ttf", 82);
	//
	M_SegoeWP_Black_0 = TTF_OpenFont("Fonts/SegoeWP_Black_0.ttf", 82);
	//
	M_SegoeWP_Bold_0 = TTF_OpenFont("Fonts/SegoeWP_Bold_0.ttf", 82);
	//
	M_SegoeWP_Light_0 = TTF_OpenFont("Fonts/SegoeWP_Light_0.ttf", 82);
	//
	M_SegoeWP_Semibold_0 = TTF_OpenFont("Fonts/SegoeWP_Semibold_0.ttf", 82);
	//
	M_SegoeWP_Semilight_0 = TTF_OpenFont("Fonts/SegoeWP_Semilight_0.ttf", 82);
	M_seguibl = TTF_OpenFont("Fonts/seguibl.ttf", 82);
	M_seguibli = TTF_OpenFont("Fonts/seguibli.ttf", 82);
	M_seguiemj = TTF_OpenFont("Fonts/seguiemj.ttf", 82);
	M_seguihis = TTF_OpenFont("Fonts/seguihis.ttf", 82);
	M_seguili = TTF_OpenFont("Fonts/seguili.ttf", 82);
	M_seguisb = TTF_OpenFont("Fonts/seguisb.ttf", 82);
	M_seguisbi = TTF_OpenFont("Fonts/seguisbi.ttf", 82);
	M_seguisli = TTF_OpenFont("Fonts/seguisli.ttf", 82);
	M_seguisym = TTF_OpenFont("Fonts/seguisym.ttf", 82);
	M_SHOWG = TTF_OpenFont("Fonts/SHOWG.ttf", 82);
	M_SNAP____ = TTF_OpenFont("Fonts/SNAP____.ttf", 82);
	M_STENCIL = TTF_OpenFont("Fonts/STENCIL.ttf", 82);
	M_sylfaen = TTF_OpenFont("Fonts/sylfaen.ttf", 82);
	M_symbol = TTF_OpenFont("Fonts/symbol.ttf", 82);
	M_tahoma = TTF_OpenFont("Fonts/tahoma.ttf", 82);
	M_tahomabd = TTF_OpenFont("Fonts/tahomabd.ttf", 82);
	M_TCB_____ = TTF_OpenFont("Fonts/TCB_____.ttf", 82);
	M_TCBI____ = TTF_OpenFont("Fonts/TCBI____.ttf", 82);
	M_TCCB____ = TTF_OpenFont("Fonts/TCCB____.ttf", 82);
	M_TCCEB = TTF_OpenFont("Fonts/TCCEB.ttf", 82);
	M_TCCM____ = TTF_OpenFont("Fonts/TCCM____.ttf", 82);
	M_TCM_____ = TTF_OpenFont("Fonts/TCM_____.ttf", 82);
	M_TCMI____ = TTF_OpenFont("Fonts/TCMI____.ttf", 82);
	M_TEMPSITC = TTF_OpenFont("Fonts/TEMPSITC.ttf", 82);
	M_times = TTF_OpenFont("Fonts/times.ttf", 82);
	M_timesbd = TTF_OpenFont("Fonts/timesbd.ttf", 82);
	M_timesbi = TTF_OpenFont("Fonts/timesbi.ttf", 82);
	M_timesi = TTF_OpenFont("Fonts/timesi.ttf", 82);
	M_trebuc = TTF_OpenFont("Fonts/trebuc.ttf", 82);
	M_trebucbd = TTF_OpenFont("Fonts/trebucbd.ttf", 82);
	M_trebucbi = TTF_OpenFont("Fonts/trebucbi.ttf", 82);
	M_trebucit = TTF_OpenFont("Fonts/trebucit.ttf", 82);
	M_verdana = TTF_OpenFont("Fonts/verdana.ttf", 82);
	M_verdanab = TTF_OpenFont("Fonts/verdanab.ttf", 82);
	M_verdanai = TTF_OpenFont("Fonts/verdanai.ttf", 82);
	M_verdanaz = TTF_OpenFont("Fonts/verdanaz.ttf", 82);
	M_VINERITC = TTF_OpenFont("Fonts/VINERITC.ttf", 82);
	M_VIVALDII = TTF_OpenFont("Fonts/VIVALDII.ttf", 82);
	M_VLADIMIR = TTF_OpenFont("Fonts/VLADIMIR.ttf", 82);
	M_webdings = TTF_OpenFont("Fonts/webdings.ttf", 82);
	M_wingding = TTF_OpenFont("Fonts/wingding.ttf", 82);
	M_WINGDNG2 = TTF_OpenFont("Fonts/WINGDNG2.ttf", 82);
	M_WINGDNG3 = TTF_OpenFont("Fonts/WINGDNG3.ttf", 82);

	Fonts.push_back(M_CalibriFont);
	Fonts.push_back(M_AGENCYB);
	Fonts.push_back(M_AGENCYR);
	Fonts.push_back(M_ALGER);
	Fonts.push_back(M_ANTQUAB);
	Fonts.push_back(M_ANTQUABI);
	Fonts.push_back(M_ANTQUAI);
	Fonts.push_back(M_arial);
	Fonts.push_back(M_arialbd);
	Fonts.push_back(M_arialbi);
	Fonts.push_back(M_ariali);
	Fonts.push_back(M_ARIALN);
	Fonts.push_back(M_ARIALNB);
	Fonts.push_back(M_ARIALNBI);
	Fonts.push_back(M_ARIALNI);
	Fonts.push_back(M_ariblk);
	Fonts.push_back(M_ARLRDBD);
	Fonts.push_back(M_bahnschrift);
	Fonts.push_back(M_BASKVILL);
	Fonts.push_back(M_BAUHS93);
	Fonts.push_back(M_BELL);
	Fonts.push_back(M_BELLB);
	Fonts.push_back(M_BELLI);
	Fonts.push_back(M_BERNHC);
	Fonts.push_back(M_BKANT);
	Fonts.push_back(M_BOD_B);
	Fonts.push_back(M_BOD_BI);
	Fonts.push_back(M_BOD_BLAI);
	Fonts.push_back(M_BOD_BLAR);
	Fonts.push_back(M_BOD_CB);
	Fonts.push_back(M_BOD_CBI);
	Fonts.push_back(M_BOD_CI);
	Fonts.push_back(M_BOD_CR);
	Fonts.push_back(M_BOD_I);
	Fonts.push_back(M_BOD_PSTC);
	Fonts.push_back(M_BOD_R);
	Fonts.push_back(M_BOOKOS);
	Fonts.push_back(M_BOOKOSB);
	Fonts.push_back(M_BOOKOSBI);
	Fonts.push_back(M_BOOKOSI);
	Fonts.push_back(M_BRADHITC);
	Fonts.push_back(M_BRITANIC);
	Fonts.push_back(M_BRLNSB);
	Fonts.push_back(M_BRLNSDB);
	Fonts.push_back(M_BRLNSR);
	Fonts.push_back(M_BROADW);
	Fonts.push_back(M_BRUSHSCI);
	Fonts.push_back(M_BSSYM7);
	Fonts.push_back(M_calibrib);
	Fonts.push_back(M_calibrii);
	Fonts.push_back(M_calibril);
	Fonts.push_back(M_calibrili);
	Fonts.push_back(M_calibriz);
	Fonts.push_back(M_CALIFB);
	Fonts.push_back(M_CALIFI);
	Fonts.push_back(M_CALIFR);
	Fonts.push_back(M_CALIST);
	Fonts.push_back(M_CALISTB);
	Fonts.push_back(M_CALISTBI);
	Fonts.push_back(M_CALISTI);
	Fonts.push_back(M_cambriab);
	Fonts.push_back(M_cambriai);
	Fonts.push_back(M_cambriaz);
	Fonts.push_back(M_Candara);
	Fonts.push_back(M_Candarab);
	Fonts.push_back(M_Candarai);
	Fonts.push_back(M_Candaral);
	Fonts.push_back(M_Candarali);
	Fonts.push_back(M_Candaraz);
	Fonts.push_back(M_CASTELAR);
	Fonts.push_back(M_CENSCBK);
	Fonts.push_back(M_CENTAUR);
	Fonts.push_back(M_CENTURY);
	Fonts.push_back(M_CHILLER);
	Fonts.push_back(M_COLONNA);
	Fonts.push_back(M_comic);
	Fonts.push_back(M_comicbd);
	Fonts.push_back(M_comici);
	Fonts.push_back(M_comicz);
	Fonts.push_back(M_consola);
	Fonts.push_back(M_consolab);
	Fonts.push_back(M_consolai);
	Fonts.push_back(M_consolaz);
	Fonts.push_back(M_constan);
	Fonts.push_back(M_constanb);
	Fonts.push_back(M_constani);
	Fonts.push_back(M_constanz);
	Fonts.push_back(M_COOPBL);
	Fonts.push_back(M_COPRGTB);
	Fonts.push_back(M_COPRGTL);
	Fonts.push_back(M_corbel);
	Fonts.push_back(M_corbelb);
	Fonts.push_back(M_corbeli);
	Fonts.push_back(M_corbell);
	Fonts.push_back(M_corbelli);
	Fonts.push_back(M_corbelz);
	Fonts.push_back(M_cour);
	Fonts.push_back(M_courbd);
	Fonts.push_back(M_courbi);
	Fonts.push_back(M_couri);
	Fonts.push_back(M_CURLZ___);
	Fonts.push_back(M_ebrima);
	Fonts.push_back(M_ebrimabd);
	Fonts.push_back(M_ELEPHNT);
	Fonts.push_back(M_ELEPHNTI);
	Fonts.push_back(M_ENGR);
	Fonts.push_back(M_ERASBD);
	Fonts.push_back(M_ERASDEMI);
	Fonts.push_back(M_ERASLGHT);
	Fonts.push_back(M_ERASMD);
	Fonts.push_back(M_FELIXTI);
	Fonts.push_back(M_FORTE);
	Fonts.push_back(M_FRABK);
	Fonts.push_back(M_FRABKIT);
	Fonts.push_back(M_FRADM);
	Fonts.push_back(M_FRADMCN);
	Fonts.push_back(M_FRADMIT);
	Fonts.push_back(M_FRAHV);
	Fonts.push_back(M_FRAHVIT);
	Fonts.push_back(M_framd);
	Fonts.push_back(M_FRAMDCN);
	Fonts.push_back(M_FRADMCN);
	Fonts.push_back(M_framdit);
	Fonts.push_back(M_FREESCPT);
	Fonts.push_back(M_FRSCRIPT);
	Fonts.push_back(M_FTLTLT);
	Fonts.push_back(M_Gabriola);
	Fonts.push_back(M_gadugi);
	Fonts.push_back(M_gadugib);
	Fonts.push_back(M_GARA);
	Fonts.push_back(M_GARABD);
	Fonts.push_back(M_GARAIT);
	Fonts.push_back(M_georgia);
	Fonts.push_back(M_georgiab);
	Fonts.push_back(M_georgiai);
	Fonts.push_back(M_georgiaz);
	Fonts.push_back(M_GIGI);
	Fonts.push_back(M_GIL_____);
	Fonts.push_back(M_GILB____);
	Fonts.push_back(M_GILBI___);
	Fonts.push_back(M_GILC____);
	Fonts.push_back(M_GILI____);
	Fonts.push_back(M_GILLUBCD);
	Fonts.push_back(M_GILSANUB);
	Fonts.push_back(M_GLECB);
	Fonts.push_back(M_GLSNECB);
	Fonts.push_back(M_GOTHIC);
	Fonts.push_back(M_GOTHICB);
	Fonts.push_back(M_GOTHICBI);
	Fonts.push_back(M_GOTHICI);
	Fonts.push_back(M_GOUDOS);
	Fonts.push_back(M_GOUDOSB);
	Fonts.push_back(M_GOUDOSI);
	Fonts.push_back(M_GOUDYSTO);
	Fonts.push_back(M_HARLOWSI);
	Fonts.push_back(M_HARNGTON);
	Fonts.push_back(M_HATTEN);
	Fonts.push_back(M_holomdl2);
	Fonts.push_back(M_HPSimplified);
	Fonts.push_back(M_HPSimplified_BdIt);
	Fonts.push_back(M_HPSimplified_It);
	Fonts.push_back(M_HPSimplified_Lt);
	Fonts.push_back(M_HPSimplified_LtIt);
	Fonts.push_back(M_HPSimplified_Rg);
	//
	Fonts.push_back(M_hpsimplifiedjpan_light);
	//
	Fonts.push_back(M_hpsimplifiedjpan_regular);
	Fonts.push_back(M_HTOWERT);
	Fonts.push_back(M_HTOWERTI);
	Fonts.push_back(M_impact);
	Fonts.push_back(M_IMPRISHA);
	Fonts.push_back(M_INFROMAN);
	Fonts.push_back(M_Inkfree);
	Fonts.push_back(M_ITCBLKAD);
	Fonts.push_back(M_ITCEDSCR);
	Fonts.push_back(M_ITCKRIST);
	Fonts.push_back(M_javatext);
	Fonts.push_back(M_JOKERMAN);
	Fonts.push_back(M_JUICE___);
	Fonts.push_back(M_KUNSTLER);
	Fonts.push_back(M_l_10646);
	Fonts.push_back(M_LATINWD);
	Fonts.push_back(M_LBRITE);
	Fonts.push_back(M_LBRITED);
	Fonts.push_back(M_LBRITEDI);
	Fonts.push_back(M_LBRITEI);
	Fonts.push_back(M_LCALLIG);
	Fonts.push_back(M_LFAX);
	Fonts.push_back(M_LFAXD);
	Fonts.push_back(M_LFAXDI);
	Fonts.push_back(M_LFAXI);
	Fonts.push_back(M_LHANDW);
	Fonts.push_back(M_LSANS);
	Fonts.push_back(M_LSANSD);
	Fonts.push_back(M_LSANSDI);
	Fonts.push_back(M_LSANSI);
	Fonts.push_back(M_LTYPE);
	Fonts.push_back(M_LTYPEB);
	Fonts.push_back(M_LTYPEBO);
	Fonts.push_back(M_LTYPEO);
	Fonts.push_back(M_lucon);
	Fonts.push_back(M_MAGNETOB);
	Fonts.push_back(M_MAIAN);
	Fonts.push_back(M_MATURASC);
	Fonts.push_back(M_MISTRAL);
	Fonts.push_back(M_mmrtext);
	Fonts.push_back(M_MOD20);
	Fonts.push_back(M_MTCORSVA);
	Fonts.push_back(M_NIAGENG);
	Fonts.push_back(M_NIAGSOL);
	Fonts.push_back(M_OCRAEXT);
	Fonts.push_back(M_OLDENGL);
	Fonts.push_back(M_ONYX);
	Fonts.push_back(M_pala);
	Fonts.push_back(M_palab);
	Fonts.push_back(M_palabi);
	Fonts.push_back(M_palai);
	Fonts.push_back(M_PALSCRI);
	Fonts.push_back(M_PAPYRUS);
	Fonts.push_back(M_PARCHM);
	Fonts.push_back(M_PER_____);
	Fonts.push_back(M_PERB____);
	Fonts.push_back(M_PERBI___);
	Fonts.push_back(M_PERI____);
	Fonts.push_back(M_PERTIBD);
	Fonts.push_back(M_PERTILI);
	Fonts.push_back(M_PLAYBILL);
	Fonts.push_back(M_POORICH);
	Fonts.push_back(M_PRISTINA);
	Fonts.push_back(M_RAGE);
	Fonts.push_back(M_RAVIE);
	Fonts.push_back(M_REFSAN);
	Fonts.push_back(M_REFSPCL);
	Fonts.push_back(M_ROCC____);
	Fonts.push_back(M_ROCCB___);
	Fonts.push_back(M_ROCK);
	Fonts.push_back(M_ROCKB);
	Fonts.push_back(M_ROCKBI);
	Fonts.push_back(M_ROCKEB);
	Fonts.push_back(M_ROCKI);
	Fonts.push_back(M_SCHLBKB);
	Fonts.push_back(M_SCHLBKBI);
	Fonts.push_back(M_SCHLBKI);
	Fonts.push_back(M_SCRIPTBL);
	Fonts.push_back(M_segmdl2);
	Fonts.push_back(M_segoepr);
	Fonts.push_back(M_segoeprb);
	Fonts.push_back(M_segoesc);
	Fonts.push_back(M_segoescb);
	Fonts.push_back(M_segoeui);
	Fonts.push_back(M_segoeuib);
	Fonts.push_back(M_segoeuii);
	Fonts.push_back(M_segoeuil);
	Fonts.push_back(M_segoeuisl);
	Fonts.push_back(M_segoeuiz);
	//
	Fonts.push_back(M_SegoeWP_Black_0);
	//
	Fonts.push_back(M_SegoeWP_Bold_0);
	//
	Fonts.push_back(M_SegoeWP_Light_0);
	//
	Fonts.push_back(M_SegoeWP_Semibold_0);
	//
	Fonts.push_back(M_seguibl);
	Fonts.push_back(M_seguibli);
	Fonts.push_back(M_seguiemj);
	Fonts.push_back(M_seguihis);
	Fonts.push_back(M_seguili);
	Fonts.push_back(M_seguisb);
	Fonts.push_back(M_seguisbi);
	Fonts.push_back(M_seguisli);
	Fonts.push_back(M_seguisym);
	Fonts.push_back(M_SHOWG);
	Fonts.push_back(M_SNAP____);
	Fonts.push_back(M_STENCIL);
	Fonts.push_back(M_sylfaen);
	Fonts.push_back(M_symbol);
	Fonts.push_back(M_tahoma);
	Fonts.push_back(M_tahomabd);
	Fonts.push_back(M_TCB_____);
	Fonts.push_back(M_TCBI____);
	Fonts.push_back(M_TCCB____);
	Fonts.push_back(M_TCCEB);
	Fonts.push_back(M_TCCM____);
	Fonts.push_back(M_TCM_____);
	Fonts.push_back(M_TCMI____);
	Fonts.push_back(M_TEMPSITC);
	Fonts.push_back(M_times);
	Fonts.push_back(M_timesbd);
	Fonts.push_back(M_timesbi);
	Fonts.push_back(M_timesi);
	Fonts.push_back(M_trebuc);
	Fonts.push_back(M_trebucbd);
	Fonts.push_back(M_trebucbi);
	Fonts.push_back(M_trebucit);
	Fonts.push_back(M_verdana);
	Fonts.push_back(M_verdanab);
	Fonts.push_back(M_verdanai);
	Fonts.push_back(M_verdanaz);
	Fonts.push_back(M_VINERITC);
	Fonts.push_back(M_VIVALDII);
	Fonts.push_back(M_VLADIMIR);
	Fonts.push_back(M_webdings);
	Fonts.push_back(M_wingding);
	Fonts.push_back(M_WINGDNG2);
	Fonts.push_back(M_WINGDNG3);

	FontsFileAdress.push_back("Fonts/calibri.ttf");
	FontsFileAdress.push_back("Fonts/AGENCYB.ttf");
	FontsFileAdress.push_back("Fonts/AGENCYR.ttf");
	FontsFileAdress.push_back("Fonts/ALGER.ttf");
	FontsFileAdress.push_back("Fonts/ANTQUAB.ttf");
	FontsFileAdress.push_back("Fonts/ANTQUABI.ttf");
	FontsFileAdress.push_back("Fonts/ANTQUAI.ttf");
	FontsFileAdress.push_back("Fonts/arial.ttf");
	FontsFileAdress.push_back("Fonts/arialbd.ttf");
	FontsFileAdress.push_back("Fonts/arialbi.ttf");
	FontsFileAdress.push_back("Fonts/ariali.ttf");
	FontsFileAdress.push_back("Fonts/ARIALN.ttf");
	FontsFileAdress.push_back("Fonts/ARIALNB.ttf");
	FontsFileAdress.push_back("Fonts/ARIALNBI.ttf");
	FontsFileAdress.push_back("Fonts/ARIALNI.ttf");
	FontsFileAdress.push_back("Fonts/ariblk.ttf");
	FontsFileAdress.push_back("Fonts/ARLRDBD.ttf");
	FontsFileAdress.push_back("Fonts/bahnschrift.ttf");
	FontsFileAdress.push_back("Fonts/BASKVILL.ttf");
	FontsFileAdress.push_back("Fonts/BAUHS93.ttf");
	FontsFileAdress.push_back("Fonts/BELL.ttf");
	FontsFileAdress.push_back("Fonts/BELLB.ttf");
	FontsFileAdress.push_back("Fonts/BELLI.ttf");
	FontsFileAdress.push_back("Fonts/BERNHC.ttf");
	FontsFileAdress.push_back("Fonts/BKANT.ttf");
	FontsFileAdress.push_back("Fonts/BOD_B.ttf");
	FontsFileAdress.push_back("Fonts/BOD_BI.ttf");
	FontsFileAdress.push_back("Fonts/BOD_BLAI.ttf");
	FontsFileAdress.push_back("Fonts/BOD_BLAR.ttf");
	FontsFileAdress.push_back("Fonts/BOD_CB.ttf");
	FontsFileAdress.push_back("Fonts/BOD_CBI.ttf");
	FontsFileAdress.push_back("Fonts/BOD_CI.ttf");
	FontsFileAdress.push_back("Fonts/BOD_CR.ttf");
	FontsFileAdress.push_back("Fonts/BOD_I.ttf");
	FontsFileAdress.push_back("Fonts/BOD_PSTC.ttf");
	FontsFileAdress.push_back("Fonts/BOD_R.ttf");
	FontsFileAdress.push_back("Fonts/BOOKOS.ttf");
	FontsFileAdress.push_back("Fonts/BOOKOSB.ttf");
	FontsFileAdress.push_back("Fonts/BOOKOSBI.ttf");
	FontsFileAdress.push_back("Fonts/BOOKOSI.ttf");
	FontsFileAdress.push_back("Fonts/BRADHITC.ttf");
	FontsFileAdress.push_back("Fonts/BRITANIC.ttf");
	FontsFileAdress.push_back("Fonts/BRLNSB.ttf");
	FontsFileAdress.push_back("Fonts/BRLNSDB.ttf");
	FontsFileAdress.push_back("Fonts/BRLNSR.ttf");
	FontsFileAdress.push_back("Fonts/BROADW.ttf");
	FontsFileAdress.push_back("Fonts/BRUSHSCI.ttf");
	FontsFileAdress.push_back("Fonts/BSSYM7.ttf");
	FontsFileAdress.push_back("Fonts/calibrib.ttf");
	FontsFileAdress.push_back("Fonts/calibrii.ttf");
	FontsFileAdress.push_back("Fonts/calibril.ttf");
	FontsFileAdress.push_back("Fonts/calibrili.ttf");
	FontsFileAdress.push_back("Fonts/calibriz.ttf");
	FontsFileAdress.push_back("Fonts/CALIFB.ttf");
	FontsFileAdress.push_back("Fonts/CALIFI.ttf");
	FontsFileAdress.push_back("Fonts/CALIFR.ttf");
	FontsFileAdress.push_back("Fonts/CALIST.ttf");
	FontsFileAdress.push_back("Fonts/CALISTB.ttf");
	FontsFileAdress.push_back("Fonts/CALISTBI.ttf");
	FontsFileAdress.push_back("Fonts/CALISTI.ttf");
	FontsFileAdress.push_back("Fonts/cambriab.ttf");
	FontsFileAdress.push_back("Fonts/cambriai.ttf");
	FontsFileAdress.push_back("Fonts/cambriaz.ttf");
	FontsFileAdress.push_back("Fonts/Candara.ttf");
	FontsFileAdress.push_back("Fonts/Candarab.ttf");
	FontsFileAdress.push_back("Fonts/Candarai.ttf");
	FontsFileAdress.push_back("Fonts/Candaral.ttf");
	FontsFileAdress.push_back("Fonts/Candarali.ttf");
	FontsFileAdress.push_back("Fonts/Candaraz.ttf");
	FontsFileAdress.push_back("Fonts/CASTELAR.ttf");
	FontsFileAdress.push_back("Fonts/CENSCBK.ttf");
	FontsFileAdress.push_back("Fonts/CENTAUR.ttf");
	FontsFileAdress.push_back("Fonts/CENTURY.ttf");
	FontsFileAdress.push_back("Fonts/CHILLER.ttf");
	FontsFileAdress.push_back("Fonts/COLONNA.ttf");
	FontsFileAdress.push_back("Fonts/comic.ttf");
	FontsFileAdress.push_back("Fonts/comicbd.ttf");
	FontsFileAdress.push_back("Fonts/comici.ttf");
	FontsFileAdress.push_back("Fonts/comicz.ttf");
	FontsFileAdress.push_back("Fonts/consola.ttf");
	FontsFileAdress.push_back("Fonts/consolab.ttf");
	FontsFileAdress.push_back("Fonts/consolai.ttf");
	FontsFileAdress.push_back("Fonts/consolaz.ttf");
	FontsFileAdress.push_back("Fonts/constan.ttf");
	FontsFileAdress.push_back("Fonts/constanb.ttf");
	FontsFileAdress.push_back("Fonts/constani.ttf");
	FontsFileAdress.push_back("Fonts/constanz.ttf");
	FontsFileAdress.push_back("Fonts/COOPBL.ttf");
	FontsFileAdress.push_back("Fonts/COPRGTB.ttf");
	FontsFileAdress.push_back("Fonts/COPRGTL.ttf");
	FontsFileAdress.push_back("Fonts/corbel.ttf");
	FontsFileAdress.push_back("Fonts/corbelb.ttf");
	FontsFileAdress.push_back("Fonts/corbeli.ttf");
	FontsFileAdress.push_back("Fonts/corbell.ttf");
	FontsFileAdress.push_back("Fonts/corbelli.ttf");
	FontsFileAdress.push_back("Fonts/corbelz.ttf");
	FontsFileAdress.push_back("Fonts/cour.ttf");
	FontsFileAdress.push_back("Fonts/courbd.ttf");
	FontsFileAdress.push_back("Fonts/courbi.ttf");
	FontsFileAdress.push_back("Fonts/couri.ttf");
	FontsFileAdress.push_back("Fonts/CURLZ___.ttf");
	FontsFileAdress.push_back("Fonts/ebrima.ttf");
	FontsFileAdress.push_back("Fonts/ebrimabd.ttf");
	FontsFileAdress.push_back("Fonts/ELEPHNT.ttf");
	FontsFileAdress.push_back("Fonts/ELEPHNTI.ttf");
	FontsFileAdress.push_back("Fonts/ENGR.ttf");
	FontsFileAdress.push_back("Fonts/ERASBD.ttf");
	FontsFileAdress.push_back("Fonts/ERASDEMI.ttf");
	FontsFileAdress.push_back("Fonts/ERASLGHT.ttf");
	FontsFileAdress.push_back("Fonts/ERASMD.ttf");
	FontsFileAdress.push_back("Fonts/FELIXTI.ttf");
	FontsFileAdress.push_back("Fonts/FORTE.ttf");
	FontsFileAdress.push_back("Fonts/FRABK.ttf");
	FontsFileAdress.push_back("Fonts/FRABKIT.ttf");
	FontsFileAdress.push_back("Fonts/FRADM.ttf");
	FontsFileAdress.push_back("Fonts/FRADMCN.ttf");
	FontsFileAdress.push_back("Fonts/FRADMIT.ttf");
	FontsFileAdress.push_back("Fonts/FRAHV.ttf");
	FontsFileAdress.push_back("Fonts/FRAHVIT.ttf");
	FontsFileAdress.push_back("Fonts/framd.ttf");
	FontsFileAdress.push_back("Fonts/FRAMDCN.ttf");
	FontsFileAdress.push_back("Fonts/framdit.ttf");
	FontsFileAdress.push_back("Fonts/FREESCPT.ttf");
	FontsFileAdress.push_back("Fonts/FRSCRIPT.ttf");
	FontsFileAdress.push_back("Fonts/FTLTLT.ttf");
	FontsFileAdress.push_back("Fonts/Gabriola.ttf");
	FontsFileAdress.push_back("Fonts/gadugi.ttf");
	FontsFileAdress.push_back("Fonts/gadugib.ttf");
	FontsFileAdress.push_back("Fonts/GARA.ttf");
	FontsFileAdress.push_back("Fonts/GARABD.ttf");
	FontsFileAdress.push_back("Fonts/GARAIT.ttf");
	FontsFileAdress.push_back("Fonts/georgia.ttf");
	FontsFileAdress.push_back("Fonts/georgiab.ttf");
	FontsFileAdress.push_back("Fonts/georgiai.ttf");
	FontsFileAdress.push_back("Fonts/georgiaz.ttf");
	FontsFileAdress.push_back("Fonts/GIGI.ttf");
	FontsFileAdress.push_back("Fonts/GIL_____.ttf");
	FontsFileAdress.push_back("Fonts/GILB____.ttf");
	FontsFileAdress.push_back("Fonts/GILBI___.ttf");
	FontsFileAdress.push_back("Fonts/GILC____.ttf");
	FontsFileAdress.push_back("Fonts/GILI____.ttf");
	FontsFileAdress.push_back("Fonts/GILLUBCD.ttf");
	FontsFileAdress.push_back("Fonts/GILSANUB.ttf");
	FontsFileAdress.push_back("Fonts/GLECB.ttf");
	FontsFileAdress.push_back("Fonts/GLSNECB.ttf");
	FontsFileAdress.push_back("Fonts/GOTHIC.ttf");
	FontsFileAdress.push_back("Fonts/GOTHICB.ttf");
	FontsFileAdress.push_back("Fonts/GOTHICBI.ttf");
	FontsFileAdress.push_back("Fonts/GOTHICI.ttf");
	FontsFileAdress.push_back("Fonts/GOUDOS.ttf");
	FontsFileAdress.push_back("Fonts/GOUDOSB.ttf");
	FontsFileAdress.push_back("Fonts/GOUDOSI.ttf");
	FontsFileAdress.push_back("Fonts/GOUDYSTO.ttf");
	FontsFileAdress.push_back("Fonts/HARLOWSI.ttf");
	FontsFileAdress.push_back("Fonts/HARNGTON.ttf");
	FontsFileAdress.push_back("Fonts/HATTEN.ttf");
	FontsFileAdress.push_back("Fonts/holomdl2.ttf");
	FontsFileAdress.push_back("Fonts/HPSimplified.ttf");
	FontsFileAdress.push_back("Fonts/HPSimplified_BdIt.ttf");
	FontsFileAdress.push_back("Fonts/HPSimplified_It.ttf");
	FontsFileAdress.push_back("Fonts/HPSimplified_Lt.ttf");
	FontsFileAdress.push_back("Fonts/HPSimplified_LtIt.ttf");
	FontsFileAdress.push_back("Fonts/HPSimplified_Rg.ttf");
	//
	FontsFileAdress.push_back("Fonts/hpsimplifiedjpan_light.ttf");
	//
	FontsFileAdress.push_back("Fonts/hpsimplifiedjpan_regular.ttf");
	FontsFileAdress.push_back("Fonts/HTOWERT.ttf");
	FontsFileAdress.push_back("Fonts/HTOWERTI.ttf");
	FontsFileAdress.push_back("Fonts/impact.ttf");
	FontsFileAdress.push_back("Fonts/IMPRISHA.ttf");
	FontsFileAdress.push_back("Fonts/INFROMAN.ttf");
	FontsFileAdress.push_back("Fonts/Inkfree.ttf");
	FontsFileAdress.push_back("Fonts/ITCBLKAD.ttf");
	FontsFileAdress.push_back("Fonts/ITCEDSCR.ttf");
	FontsFileAdress.push_back("Fonts/ITCKRIST.ttf");
	FontsFileAdress.push_back("Fonts/javatext.ttf");
	FontsFileAdress.push_back("Fonts/JOKERMAN.ttf");
	FontsFileAdress.push_back("Fonts/JUICE___.ttf");
	FontsFileAdress.push_back("Fonts/KUNSTLER.ttf");
	FontsFileAdress.push_back("Fonts/l_10646.ttf");
	FontsFileAdress.push_back("Fonts/LATINWD.ttf");
	FontsFileAdress.push_back("Fonts/LBRITE.ttf");
	FontsFileAdress.push_back("Fonts/LBRITED.ttf");
	FontsFileAdress.push_back("Fonts/LBRITEDI.ttf");
	FontsFileAdress.push_back("Fonts/LBRITEI.ttf");
	FontsFileAdress.push_back("Fonts/LCALLIG.ttf");
	FontsFileAdress.push_back("Fonts/LFAX.ttf");
	FontsFileAdress.push_back("Fonts/LFAXD.ttf");
	FontsFileAdress.push_back("Fonts/LFAXDI.ttf");
	FontsFileAdress.push_back("Fonts/LFAXI.ttf");
	FontsFileAdress.push_back("Fonts/LHANDW.ttf");
	FontsFileAdress.push_back("Fonts/LSANS.ttf");
	FontsFileAdress.push_back("Fonts/LSANSD.ttf");
	FontsFileAdress.push_back("Fonts/LSANSDI.ttf");
	FontsFileAdress.push_back("Fonts/LSANSI.ttf");
	FontsFileAdress.push_back("Fonts/LTYPE.ttf");
	FontsFileAdress.push_back("Fonts/LTYPEB.ttf");
	FontsFileAdress.push_back("Fonts/LTYPEBO.ttf");
	FontsFileAdress.push_back("Fonts/LTYPEO.ttf");
	FontsFileAdress.push_back("Fonts/lucon.ttf");
	FontsFileAdress.push_back("Fonts/MAGNETOB.ttf");
	FontsFileAdress.push_back("Fonts/MAIAN.ttf");
	FontsFileAdress.push_back("Fonts/MATURASC.ttf");
	FontsFileAdress.push_back("Fonts/MISTRAL.ttf");
	FontsFileAdress.push_back("Fonts/mmrtext.ttf");
	FontsFileAdress.push_back("Fonts/MOD20.ttf");
	FontsFileAdress.push_back("Fonts/MTCORSVA.ttf");
	FontsFileAdress.push_back("Fonts/NIAGENG.ttf");
	FontsFileAdress.push_back("Fonts/NIAGSOL.ttf");
	FontsFileAdress.push_back("Fonts/OCRAEXT.ttf");
	FontsFileAdress.push_back("Fonts/OLDENGL.ttf");
	FontsFileAdress.push_back("Fonts/ONYX.ttf");
	FontsFileAdress.push_back("Fonts/pala.ttf");
	FontsFileAdress.push_back("Fonts/palab.ttf");
	FontsFileAdress.push_back("Fonts/palabi.ttf");
	FontsFileAdress.push_back("Fonts/palai.ttf");
	FontsFileAdress.push_back("Fonts/PALSCRI.ttf");
	FontsFileAdress.push_back("Fonts/PAPYRUS.ttf");
	FontsFileAdress.push_back("Fonts/PARCHM.ttf");
	FontsFileAdress.push_back("Fonts/PER_____.ttf");
	FontsFileAdress.push_back("Fonts/PERB____.ttf");
	FontsFileAdress.push_back("Fonts/PERBI___.ttf");
	FontsFileAdress.push_back("Fonts/PERI____.ttf");
	FontsFileAdress.push_back("Fonts/PERTIBD.ttf");
	FontsFileAdress.push_back("Fonts/PERTILI.ttf");
	FontsFileAdress.push_back("Fonts/PLAYBILL.ttf");
	FontsFileAdress.push_back("Fonts/POORICH.ttf");
	FontsFileAdress.push_back("Fonts/PRISTINA.ttf");
	FontsFileAdress.push_back("Fonts/RAGE.ttf");
	FontsFileAdress.push_back("Fonts/RAVIE.ttf");
	FontsFileAdress.push_back("Fonts/REFSAN.ttf");
	FontsFileAdress.push_back("Fonts/REFSPCL.ttf");
	FontsFileAdress.push_back("Fonts/ROCC____.ttf");
	FontsFileAdress.push_back("Fonts/ROCCB___.ttf");
	FontsFileAdress.push_back("Fonts/ROCK.ttf");
	FontsFileAdress.push_back("Fonts/ROCKB.ttf");
	FontsFileAdress.push_back("Fonts/ROCKBI.ttf");
	FontsFileAdress.push_back("Fonts/ROCKEB.ttf");
	FontsFileAdress.push_back("Fonts/ROCKI.ttf");
	FontsFileAdress.push_back("Fonts/SCHLBKB.ttf");
	FontsFileAdress.push_back("Fonts/SCHLBKBI.ttf");
	FontsFileAdress.push_back("Fonts/SCHLBKI.ttf");
	FontsFileAdress.push_back("Fonts/SCRIPTBL.ttf");
	FontsFileAdress.push_back("Fonts/segmdl2.ttf");
	FontsFileAdress.push_back("Fonts/segoepr.ttf");
	FontsFileAdress.push_back("Fonts/segoeprb.ttf");
	FontsFileAdress.push_back("Fonts/segoesc.ttf");
	FontsFileAdress.push_back("Fonts/segoescb.ttf");
	FontsFileAdress.push_back("Fonts/segoeui.ttf");
	FontsFileAdress.push_back("Fonts/segoeuib.ttf");
	FontsFileAdress.push_back("Fonts/segoeuii.ttf");
	FontsFileAdress.push_back("Fonts/segoeuil.ttf");
	FontsFileAdress.push_back("Fonts/segoeuisl.ttf");
	FontsFileAdress.push_back("Fonts/segoeuiz.ttf");
	//
	FontsFileAdress.push_back("Fonts/SegoeWP_Black_0.ttf");
	//
	FontsFileAdress.push_back("Fonts/SegoeWP_Bold_0.ttf");
	//
	FontsFileAdress.push_back("Fonts/SegoeWP_Light_0.ttf");
	//
	FontsFileAdress.push_back("Fonts/SegoeWP_Semibold_0.ttf");
	//
	FontsFileAdress.push_back("Fonts/SegoeWP_Semilight_0.ttf");
	FontsFileAdress.push_back("Fonts/seguibl.ttf");
	FontsFileAdress.push_back("Fonts/seguibli.ttf");
	FontsFileAdress.push_back("Fonts/seguiemj.ttf");
	FontsFileAdress.push_back("Fonts/seguihis.ttf");
	FontsFileAdress.push_back("Fonts/seguili.ttf");
	FontsFileAdress.push_back("Fonts/seguisb.ttf");
	FontsFileAdress.push_back("Fonts/seguisbi.ttf");
	FontsFileAdress.push_back("Fonts/seguisli.ttf");
	FontsFileAdress.push_back("Fonts/seguisym.ttf");
	FontsFileAdress.push_back("Fonts/SHOWG.ttf");
	FontsFileAdress.push_back("Fonts/SNAP____.ttf");
	FontsFileAdress.push_back("Fonts/STENCIL.ttf");
	FontsFileAdress.push_back("Fonts/sylfaen.ttf");
	FontsFileAdress.push_back("Fonts/symbol.ttf");
	FontsFileAdress.push_back("Fonts/tahoma.ttf");
	FontsFileAdress.push_back("Fonts/tahomabd.ttf");
	FontsFileAdress.push_back("Fonts/TCB_____.ttf");
	FontsFileAdress.push_back("Fonts/TCBI____.ttf");
	FontsFileAdress.push_back("Fonts/TCCB____.ttf");
	FontsFileAdress.push_back("Fonts/TCCEB.ttf");
	FontsFileAdress.push_back("Fonts/TCCM____.ttf");
	FontsFileAdress.push_back("Fonts/TCM_____.ttf");
	FontsFileAdress.push_back("Fonts/TCMI____.ttf");
	FontsFileAdress.push_back("Fonts/TEMPSITC.ttf");
	FontsFileAdress.push_back("Fonts/times.ttf");
	FontsFileAdress.push_back("Fonts/timesbd.ttf");
	FontsFileAdress.push_back("Fonts/timesbi.ttf");
	FontsFileAdress.push_back("Fonts/timesi.ttf");
	FontsFileAdress.push_back("Fonts/trebuc.ttf");
	FontsFileAdress.push_back("Fonts/trebucbd.ttf");
	FontsFileAdress.push_back("Fonts/trebucbi.ttf");
	FontsFileAdress.push_back("Fonts/trebucit.ttf");
	FontsFileAdress.push_back("Fonts/verdana.ttf");
	FontsFileAdress.push_back("Fonts/verdanab.ttf");
	FontsFileAdress.push_back("Fonts/verdanai.ttf");
	FontsFileAdress.push_back("Fonts/verdanaz.ttf");
	FontsFileAdress.push_back("Fonts/VINERITC.ttf");
	FontsFileAdress.push_back("Fonts/VIVALDII.ttf");
	FontsFileAdress.push_back("Fonts/VLADIMIR.ttf");
	FontsFileAdress.push_back("Fonts/webdings.ttf");
	FontsFileAdress.push_back("Fonts/wingding.ttf");
	FontsFileAdress.push_back("Fonts/WINGDNG2.ttf");
	FontsFileAdress.push_back("Fonts/WINGDNG3.ttf");

	for (int i = 0; i < Fonts.size(); i++)
	{
		if (Fonts[i] == nullptr)
		{
			std::string LogMessage = "Couldn't Load All The Fonts. " + std::string(SDL_GetError());

			ErrorReporter::LogMessage("Error", LogMessage.c_str());
		}
	}
}

SDL_Texture* TextTexture = nullptr;
SDL_Surface* TextSurface = nullptr;

SDL_Texture* RenderText::CreateNewTexture(const char* Text, SDL_Rect TextRect, fonts font, SDL_Colour textColour, int FontSize)
{
	bool ResetFont = false;

	if (FontSize == 82)
	{
		ResetFont = false;
	}
	else
	{
		ResetFont = true;
	}

	if (ResetFont)
	{
		Fonts[font] = TTF_OpenFont(FontsFileAdress[font], FontSize);
	}

	SDL_DestroyTexture(TextTexture);

	TextSurface = TTF_RenderText_Blended_Wrapped(Fonts[font], Text, textColour, TextRect.w);

	TextTexture = SDL_CreateTextureFromSurface(Init::Renderer, TextSurface);

	SDL_QueryTexture(TextTexture, nullptr, nullptr, &TextRect.w, &TextRect.h);
	SDL_FreeSurface(TextSurface);

	if (ResetFont)
	{
		Fonts[font] = TTF_OpenFont(FontsFileAdress[font], 82);
	}

	return TextTexture;
}

void RenderText::Clean()
{
	TTF_Quit();
}
