// This is a personal academic project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com

//This Is A Beast Engine File Which Has The License Apache 2.0

#include <iostream>
#include <vector>
#include <string>
#include "RenderText.h"
#include "Init.h"
#include "ErrorReporter.h"

TTF_Font* CalibriFont = nullptr;
TTF_Font* AGENCYB = nullptr;
TTF_Font* AGENCYR = nullptr;
TTF_Font* ALGER = nullptr;
TTF_Font* ANTQUAB = nullptr;
TTF_Font* ANTQUABI = nullptr;
TTF_Font* ANTQUAI = nullptr;
TTF_Font* arial = nullptr;
TTF_Font* arialbd = nullptr;
TTF_Font* arialbi = nullptr;
TTF_Font* ariali = nullptr;
TTF_Font* ARIALN = nullptr;
TTF_Font* ARIALNB = nullptr;
TTF_Font* ARIALNBI = nullptr;
TTF_Font* ARIALNI = nullptr;
TTF_Font* ariblk = nullptr;
TTF_Font* ARLRDBD = nullptr;
TTF_Font* bahnschrift = nullptr;
TTF_Font* BASKVILL = nullptr;
TTF_Font* BAUHS93 = nullptr;
TTF_Font* BELL = nullptr;
TTF_Font* BELLB = nullptr;
TTF_Font* BELLI = nullptr;
TTF_Font* BERNHC = nullptr;
TTF_Font* BKANT = nullptr;
TTF_Font* BOD_B = nullptr;
TTF_Font* BOD_BI = nullptr;
TTF_Font* BOD_BLAI = nullptr;
TTF_Font* BOD_BLAR = nullptr;
TTF_Font* BOD_CB = nullptr;
TTF_Font* BOD_CBI = nullptr;
TTF_Font* BOD_CI = nullptr;
TTF_Font* BOD_CR = nullptr;
TTF_Font* BOD_I = nullptr;
TTF_Font* BOD_PSTC = nullptr;
TTF_Font* BOD_R = nullptr;
TTF_Font* BOOKOS = nullptr;
TTF_Font* BOOKOSB = nullptr;
TTF_Font* BOOKOSBI = nullptr;
TTF_Font* BOOKOSI = nullptr;
TTF_Font* BRADHITC = nullptr;
TTF_Font* BRITANIC = nullptr;
TTF_Font* BRLNSB = nullptr;
TTF_Font* BRLNSDB = nullptr;
TTF_Font* BRLNSR = nullptr;
TTF_Font* BROADW = nullptr;
TTF_Font* BRUSHSCI = nullptr;
TTF_Font* BSSYM7 = nullptr;
TTF_Font* calibrib = nullptr;
TTF_Font* calibrii = nullptr;
TTF_Font* calibril = nullptr;
TTF_Font* calibrili = nullptr;
TTF_Font* calibriz = nullptr;
TTF_Font* CALIFB = nullptr;
TTF_Font* CALIFI = nullptr;
TTF_Font* CALIFR = nullptr;
TTF_Font* CALIST = nullptr;
TTF_Font* CALISTB = nullptr;
TTF_Font* CALISTBI = nullptr;
TTF_Font* CALISTI = nullptr;
TTF_Font* cambriab = nullptr;
TTF_Font* cambriai = nullptr;
TTF_Font* cambriaz = nullptr;
TTF_Font* Candara = nullptr;
TTF_Font* Candarab = nullptr;
TTF_Font* Candarai = nullptr;
TTF_Font* Candaral = nullptr;
TTF_Font* Candarali = nullptr;
TTF_Font* Candaraz = nullptr;
TTF_Font* CASTELAR = nullptr;
TTF_Font* CENSCBK = nullptr;
TTF_Font* CENTAUR = nullptr;
TTF_Font* CENTURY = nullptr;
TTF_Font* CHILLER = nullptr;
TTF_Font* COLONNA = nullptr;
TTF_Font* comic = nullptr;
TTF_Font* comicbd = nullptr;
TTF_Font* comici = nullptr;
TTF_Font* comicz = nullptr;
TTF_Font* consola = nullptr;
TTF_Font* consolab = nullptr;
TTF_Font* consolai = nullptr;
TTF_Font* consolaz = nullptr;
TTF_Font* constan = nullptr;
TTF_Font* constanb = nullptr;
TTF_Font* constani = nullptr;
TTF_Font* constanz = nullptr;
TTF_Font* COOPBL = nullptr;
TTF_Font* COPRGTB = nullptr;
TTF_Font* COPRGTL = nullptr;
TTF_Font* corbel = nullptr;
TTF_Font* corbelb = nullptr;
TTF_Font* corbeli = nullptr;
TTF_Font* corbell = nullptr;
TTF_Font* corbelli = nullptr;
TTF_Font* corbelz = nullptr;
TTF_Font* cour = nullptr;
TTF_Font* courbd = nullptr;
TTF_Font* courbi = nullptr;
TTF_Font* couri = nullptr;
TTF_Font* CURLZ___ = nullptr;
TTF_Font* ebrima = nullptr;
TTF_Font* ebrimabd = nullptr;
TTF_Font* ELEPHNT = nullptr;
TTF_Font* ELEPHNTI = nullptr;
TTF_Font* ENGR = nullptr;
TTF_Font* ERASBD = nullptr;
TTF_Font* ERASDEMI = nullptr;
TTF_Font* ERASLGHT = nullptr;
TTF_Font* ERASMD = nullptr;
TTF_Font* FELIXTI = nullptr;
TTF_Font* FORTE = nullptr;
TTF_Font* FRABK = nullptr;
TTF_Font* FRABKIT = nullptr;
TTF_Font* FRADM = nullptr;
TTF_Font* FRADMCN = nullptr;
TTF_Font* FRADMIT = nullptr;
TTF_Font* FRAHV = nullptr;
TTF_Font* FRAHVIT = nullptr;
TTF_Font* framd = nullptr;
TTF_Font* FRAMDCN = nullptr;
TTF_Font* framdit = nullptr;
TTF_Font* FREESCPT = nullptr;
TTF_Font* FRSCRIPT = nullptr;
TTF_Font* FTLTLT = nullptr;
TTF_Font* Gabriola = nullptr;
TTF_Font* gadugi = nullptr;
TTF_Font* gadugib = nullptr;
TTF_Font* GARA = nullptr;
TTF_Font* GARABD = nullptr;
TTF_Font* GARAIT = nullptr;
TTF_Font* georgia = nullptr;
TTF_Font* georgiab = nullptr;
TTF_Font* georgiai = nullptr;
TTF_Font* georgiaz = nullptr;
TTF_Font* GIGI = nullptr;
TTF_Font* GIL_____ = nullptr;
TTF_Font* GILB____ = nullptr;
TTF_Font* GILBI___ = nullptr;
TTF_Font* GILC____ = nullptr;
TTF_Font* GILI____ = nullptr;
TTF_Font* GILLUBCD = nullptr;
TTF_Font* GILSANUB = nullptr;
TTF_Font* GLECB = nullptr;
TTF_Font* GLSNECB = nullptr;
TTF_Font* GOTHIC = nullptr;
TTF_Font* GOTHICB = nullptr;
TTF_Font* GOTHICBI = nullptr;
TTF_Font* GOTHICI = nullptr;
TTF_Font* GOUDOS = nullptr;
TTF_Font* GOUDOSB = nullptr;
TTF_Font* GOUDOSI = nullptr;
TTF_Font* GOUDYSTO = nullptr;
TTF_Font* HARLOWSI = nullptr;
TTF_Font* HARNGTON = nullptr;
TTF_Font* HATTEN = nullptr;
TTF_Font* holomdl2 = nullptr;
TTF_Font* HPSimplified = nullptr;
TTF_Font* HPSimplified_BdIt = nullptr;
TTF_Font* HPSimplified_It = nullptr;
TTF_Font* HPSimplified_Lt = nullptr;
TTF_Font* HPSimplified_LtIt = nullptr;
TTF_Font* HPSimplified_Rg = nullptr;
//
TTF_Font* hpsimplifiedjpan_light = nullptr;
//
TTF_Font* hpsimplifiedjpan_regular = nullptr;
TTF_Font* HTOWERT = nullptr;
TTF_Font* HTOWERTI = nullptr;
TTF_Font* impact = nullptr;
TTF_Font* IMPRISHA = nullptr;
TTF_Font* INFROMAN = nullptr;
TTF_Font* Inkfree = nullptr;
TTF_Font* ITCBLKAD = nullptr;
TTF_Font* ITCEDSCR = nullptr;
TTF_Font* ITCKRIST = nullptr;
TTF_Font* javatext = nullptr;
TTF_Font* JOKERMAN = nullptr;
TTF_Font* JUICE___ = nullptr;
TTF_Font* KUNSTLER = nullptr;
TTF_Font* l_10646 = nullptr;
TTF_Font* LATINWD = nullptr;
TTF_Font* LBRITE = nullptr;
TTF_Font* LBRITED = nullptr;
TTF_Font* LBRITEDI = nullptr;
TTF_Font* LBRITEI = nullptr;
TTF_Font* LCALLIG = nullptr;
TTF_Font* LFAX = nullptr;
TTF_Font* LFAXD = nullptr;
TTF_Font* LFAXDI = nullptr;
TTF_Font* LFAXI = nullptr;
TTF_Font* LHANDW = nullptr;
TTF_Font* LSANS = nullptr;
TTF_Font* LSANSD = nullptr;
TTF_Font* LSANSDI = nullptr;
TTF_Font* LSANSI = nullptr;
TTF_Font* LTYPE = nullptr;
TTF_Font* LTYPEB = nullptr;
TTF_Font* LTYPEBO = nullptr;
TTF_Font* LTYPEO = nullptr;
TTF_Font* lucon = nullptr;
TTF_Font* MAGNETOB = nullptr;
TTF_Font* MAIAN = nullptr;
TTF_Font* MATURASC = nullptr;
TTF_Font* MISTRAL = nullptr;
TTF_Font* mmrtext = nullptr;
TTF_Font* MOD20 = nullptr;
TTF_Font* MTCORSVA = nullptr;
TTF_Font* NIAGENG = nullptr;
TTF_Font* NIAGSOL = nullptr;
TTF_Font* OCRAEXT = nullptr;
TTF_Font* OLDENGL = nullptr;
TTF_Font* ONYX = nullptr;
TTF_Font* pala = nullptr;
TTF_Font* palab = nullptr;
TTF_Font* palabi = nullptr;
TTF_Font* palai = nullptr;
TTF_Font* PALSCRI = nullptr;
TTF_Font* PAPYRUS = nullptr;
TTF_Font* PARCHM = nullptr;
TTF_Font* PER_____ = nullptr;
TTF_Font* PERB____ = nullptr;
TTF_Font* PERBI___ = nullptr;
TTF_Font* PERI____ = nullptr;
TTF_Font* PERTIBD = nullptr;
TTF_Font* PERTILI = nullptr;
TTF_Font* PLAYBILL = nullptr;
TTF_Font* POORICH = nullptr;
TTF_Font* PRISTINA = nullptr;
TTF_Font* RAGE = nullptr;
TTF_Font* RAVIE = nullptr;
TTF_Font* REFSAN = nullptr;
TTF_Font* REFSPCL = nullptr;
TTF_Font* ROCC____ = nullptr;
TTF_Font* ROCCB___ = nullptr;
TTF_Font* ROCK = nullptr;
TTF_Font* ROCKB = nullptr;
TTF_Font* ROCKBI = nullptr;
TTF_Font* ROCKEB = nullptr;
TTF_Font* ROCKI = nullptr;
TTF_Font* SCHLBKB = nullptr;
TTF_Font* SCHLBKBI = nullptr;
TTF_Font* SCHLBKI = nullptr;
TTF_Font* SCRIPTBL = nullptr;
TTF_Font* segmdl2 = nullptr;
TTF_Font* segoepr = nullptr;
TTF_Font* segoeprb = nullptr;
TTF_Font* segoesc = nullptr;
TTF_Font* segoescb = nullptr;
TTF_Font* segoeui = nullptr;
TTF_Font* segoeuib = nullptr;
TTF_Font* segoeuii = nullptr;
TTF_Font* segoeuil = nullptr;
TTF_Font* segoeuisl = nullptr;
TTF_Font* segoeuiz = nullptr;
//
TTF_Font* SegoeWP_Black_0 = nullptr;
//
TTF_Font* SegoeWP_Bold_0 = nullptr;
//
TTF_Font* SegoeWP_Light_0 = nullptr;
//
TTF_Font* SegoeWP_Semibold_0 = nullptr;
//
TTF_Font* SegoeWP_Semilight_0 = nullptr;
TTF_Font* seguibl = nullptr;
TTF_Font* seguibli = nullptr;
TTF_Font* seguiemj = nullptr;
TTF_Font* seguihis = nullptr;
TTF_Font* seguili = nullptr;
TTF_Font* seguisb = nullptr;
TTF_Font* seguisbi = nullptr;
TTF_Font* seguisli = nullptr;
TTF_Font* seguisym = nullptr;
TTF_Font* SHOWG = nullptr;
TTF_Font* SNAP____ = nullptr;
TTF_Font* STENCIL = nullptr;
TTF_Font* sylfaen = nullptr;
TTF_Font* symbol = nullptr;
TTF_Font* tahoma = nullptr;
TTF_Font* tahomabd = nullptr;
TTF_Font* TCB_____ = nullptr;
TTF_Font* TCBI____ = nullptr;
TTF_Font* TCCB____ = nullptr;
TTF_Font* TCCEB = nullptr;
TTF_Font* TCCM____ = nullptr;
TTF_Font* TCM_____ = nullptr;
TTF_Font* TCMI____ = nullptr;
TTF_Font* TEMPSITC = nullptr;
TTF_Font* times = nullptr;
TTF_Font* timesbd = nullptr;
TTF_Font* timesbi = nullptr;
TTF_Font* timesi = nullptr;
TTF_Font* trebuc = nullptr;
TTF_Font* trebucbd = nullptr;
TTF_Font* trebucbi = nullptr;
TTF_Font* trebucit = nullptr;
TTF_Font* verdana = nullptr;
TTF_Font* verdanab = nullptr;
TTF_Font* verdanai = nullptr;
TTF_Font* verdanaz = nullptr;
TTF_Font* VINERITC = nullptr;
TTF_Font* VIVALDII = nullptr;
TTF_Font* VLADIMIR = nullptr;
TTF_Font* webdings = nullptr;
TTF_Font* wingding = nullptr;
TTF_Font* WINGDNG2 = nullptr;
TTF_Font* WINGDNG3 = nullptr;

std::vector<TTF_Font*> Fonts;

int RenderText::Init()
{
	if (TTF_Init() != 0)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

void RenderText::Load()
{
	CalibriFont = TTF_OpenFont("Fonts/calibri.ttf", 82);
	AGENCYB = TTF_OpenFont("Fonts/AGENCYB.ttf", 82);
	AGENCYR = TTF_OpenFont("Fonts/AGENCYR.ttf", 82);
	ALGER = TTF_OpenFont("Fonts/ALGER.ttf", 82);
	ANTQUAB = TTF_OpenFont("Fonts/ANTQUAB.ttf", 82);
	ANTQUABI = TTF_OpenFont("Fonts/ANTQUABI.ttf", 82);
	ANTQUAI = TTF_OpenFont("Fonts/ANTQUAI.ttf", 82);
	arial = TTF_OpenFont("Fonts/arial.ttf", 82);
	arialbd = TTF_OpenFont("Fonts/arialbd.ttf", 82);
	arialbi = TTF_OpenFont("Fonts/arialbi.ttf", 82);
	ariali = TTF_OpenFont("Fonts/ariali.ttf", 82);
	ARIALN = TTF_OpenFont("Fonts/ARIALN.ttf", 82);
	ARIALNB = TTF_OpenFont("Fonts/ARIALNB.ttf", 82);
	ARIALNBI = TTF_OpenFont("Fonts/ARIALNBI.ttf", 82);
	ARIALNI = TTF_OpenFont("Fonts/ARIALNI.ttf", 82);
	ariblk = TTF_OpenFont("Fonts/ariblk.ttf", 82);
	ARLRDBD = TTF_OpenFont("Fonts/ARLRDBD.ttf", 82);
	bahnschrift = TTF_OpenFont("Fonts/bahnschrift.ttf", 82);
	BASKVILL = TTF_OpenFont("Fonts/BASKVILL.ttf", 82);
	BAUHS93 = TTF_OpenFont("Fonts/BAUHS93.ttf", 82);
	BELL = TTF_OpenFont("Fonts/BELL.ttf", 82);
	BELLB = TTF_OpenFont("Fonts/BELLB.ttf", 82);
	BELLI = TTF_OpenFont("Fonts/BELLI.ttf", 82);
	BERNHC = TTF_OpenFont("Fonts/BERNHC.ttf", 82);
	BKANT = TTF_OpenFont("Fonts/BKANT.ttf", 82);
	BOD_B = TTF_OpenFont("Fonts/BOD_B.ttf", 82);
	BOD_BI = TTF_OpenFont("Fonts/BOD_BI.ttf", 82);
	BOD_BLAI = TTF_OpenFont("Fonts/BOD_BLAI.ttf", 82);
	BOD_BLAR = TTF_OpenFont("Fonts/BOD_BLAR.ttf", 82);
	BOD_CB = TTF_OpenFont("Fonts/BOD_CB.ttf", 82);
	BOD_CBI = TTF_OpenFont("Fonts/BOD_CBI.ttf", 82);
	BOD_CI = TTF_OpenFont("Fonts/BOD_CI.ttf", 82);
	BOD_CR = TTF_OpenFont("Fonts/BOD_CR.ttf", 82);
	BOD_I = TTF_OpenFont("Fonts/BOD_I.ttf", 82);
	BOD_PSTC = TTF_OpenFont("Fonts/BOD_PSTC.ttf", 82);
	BOD_R = TTF_OpenFont("Fonts/BOD_R.ttf", 82);
	BOOKOS = TTF_OpenFont("Fonts/BOOKOS.ttf", 82);
	BOOKOSB = TTF_OpenFont("Fonts/BOOKOSB.ttf", 82);
	BOOKOSBI = TTF_OpenFont("Fonts/BOOKOSBI.ttf", 82);
	BOOKOSI = TTF_OpenFont("Fonts/BOOKOSI.ttf", 82);
	BRADHITC = TTF_OpenFont("Fonts/BRADHITC.ttf", 82);
	BRITANIC = TTF_OpenFont("Fonts/BRITANIC.ttf", 82);
	BRLNSB = TTF_OpenFont("Fonts/BRLNSB.ttf", 82);
	BRLNSDB = TTF_OpenFont("Fonts/BRLNSDB.ttf", 82);
	BRLNSR = TTF_OpenFont("Fonts/BRLNSR.ttf", 82);
	BROADW = TTF_OpenFont("Fonts/BROADW.ttf", 82);
	BRUSHSCI = TTF_OpenFont("Fonts/BRUSHSCI.ttf", 82);
	BSSYM7 = TTF_OpenFont("Fonts/BSSYM7.ttf", 82);
	calibrib = TTF_OpenFont("Fonts/calibrib.ttf", 82);
	calibrii = TTF_OpenFont("Fonts/calibrii.ttf", 82);
	calibril = TTF_OpenFont("Fonts/calibril.ttf", 82);
	calibrili = TTF_OpenFont("Fonts/calibrili.ttf", 82);
	calibriz = TTF_OpenFont("Fonts/calibriz.ttf", 82);
	CALIFB = TTF_OpenFont("Fonts/CALIFB.ttf", 82);
	CALIFI = TTF_OpenFont("Fonts/CALIFI.ttf", 82);
	CALIFR = TTF_OpenFont("Fonts/CALIFR.ttf", 82);
	CALIST = TTF_OpenFont("Fonts/CALIST.ttf", 82);
	CALISTB = TTF_OpenFont("Fonts/CALISTB.ttf", 82);
	CALISTBI = TTF_OpenFont("Fonts/CALISTBI.ttf", 82);
	CALISTI = TTF_OpenFont("Fonts/CALISTI.ttf", 82);
	cambriab = TTF_OpenFont("Fonts/cambriab.ttf", 82);
	cambriai = TTF_OpenFont("Fonts/cambriai.ttf", 82);
	cambriaz = TTF_OpenFont("Fonts/cambriaz.ttf", 82);
	Candara = TTF_OpenFont("Fonts/Candara.ttf", 82);
	Candarab = TTF_OpenFont("Fonts/Candarab.ttf", 82);
	Candarai = TTF_OpenFont("Fonts/Candarai.ttf", 82);
	Candaral = TTF_OpenFont("Fonts/Candaral.ttf", 82);
	Candarali = TTF_OpenFont("Fonts/Candarali.ttf", 82);
	Candaraz = TTF_OpenFont("Fonts/Candaraz.ttf", 82);
	CASTELAR = TTF_OpenFont("Fonts/CASTELAR.ttf", 82);
	CENSCBK = TTF_OpenFont("Fonts/CENSCBK.ttf", 82);
	CENTAUR = TTF_OpenFont("Fonts/CENTAUR.ttf", 82);
	CENTURY = TTF_OpenFont("Fonts/CENTURY.ttf", 82);
	CHILLER = TTF_OpenFont("Fonts/CHILLER.ttf", 82);
	COLONNA = TTF_OpenFont("Fonts/COLONNA.ttf", 82);
	comic = TTF_OpenFont("Fonts/comic.ttf", 82);
	comicbd = TTF_OpenFont("Fonts/comicbd.ttf", 82);
	comici = TTF_OpenFont("Fonts/comici.ttf", 82);
	comicz = TTF_OpenFont("Fonts/comicz.ttf", 82);
	consola = TTF_OpenFont("Fonts/consola.ttf", 82);
	consolab = TTF_OpenFont("Fonts/consolab.ttf", 82);
	consolai = TTF_OpenFont("Fonts/consolai.ttf", 82);
	consolaz = TTF_OpenFont("Fonts/consolaz.ttf", 82);
	constan = TTF_OpenFont("Fonts/constan.ttf", 82);
	constanb = TTF_OpenFont("Fonts/constanb.ttf", 82);
	constani = TTF_OpenFont("Fonts/constani.ttf", 82);
	constanz = TTF_OpenFont("Fonts/constanz.ttf", 82);
	COOPBL = TTF_OpenFont("Fonts/COOPBL.ttf", 82);
	COPRGTB = TTF_OpenFont("Fonts/COPRGTB.ttf", 82);
	COPRGTL = TTF_OpenFont("Fonts/COPRGTL.ttf", 82);
	corbel = TTF_OpenFont("Fonts/corbel.ttf", 82);
	corbelb = TTF_OpenFont("Fonts/corbelb.ttf", 82);
	corbeli = TTF_OpenFont("Fonts/corbeli.ttf", 82);
	corbell = TTF_OpenFont("Fonts/corbell.ttf", 82);
	corbelli = TTF_OpenFont("Fonts/corbelli.ttf", 82);
	corbelz = TTF_OpenFont("Fonts/corbelz.ttf", 82);
	cour = TTF_OpenFont("Fonts/cour.ttf", 82);
	courbd = TTF_OpenFont("Fonts/courbd.ttf", 82);
	courbi = TTF_OpenFont("Fonts/courbi.ttf", 82);
	couri = TTF_OpenFont("Fonts/couri.ttf", 82);
	CURLZ___ = TTF_OpenFont("Fonts/CURLZ___.ttf", 82);
	ebrima = TTF_OpenFont("Fonts/ebrima.ttf", 82);
	ebrimabd = TTF_OpenFont("Fonts/ebrimabd.ttf", 82);
	ELEPHNT = TTF_OpenFont("Fonts/ELEPHNT.ttf", 82);
	ELEPHNTI = TTF_OpenFont("Fonts/ELEPHNTI.ttf", 82);
	ENGR = TTF_OpenFont("Fonts/ENGR.ttf", 82);
	ERASBD = TTF_OpenFont("Fonts/ERASBD.ttf", 82);
	ERASDEMI = TTF_OpenFont("Fonts/ERASDEMI.ttf", 82);
	ERASLGHT = TTF_OpenFont("Fonts/ERASLGHT.ttf", 82);
	ERASMD = TTF_OpenFont("Fonts/ERASMD.ttf", 82);
	FELIXTI = TTF_OpenFont("Fonts/FELIXTI.ttf", 82);
	FORTE = TTF_OpenFont("Fonts/FORTE.ttf", 82);
	FRABK = TTF_OpenFont("Fonts/FRABK.ttf", 82);
	FRABKIT = TTF_OpenFont("Fonts/FRABKIT.ttf", 82);
	FRADM = TTF_OpenFont("Fonts/FRADM.ttf", 82);
	FRADMCN = TTF_OpenFont("Fonts/FRADMCN.ttf", 82);
	FRADMIT = TTF_OpenFont("Fonts/FRADMIT.ttf", 82);
	FRAHV = TTF_OpenFont("Fonts/FRAHV.ttf", 82);
	FRAHVIT = TTF_OpenFont("Fonts/FRAHVIT.ttf", 82);
	framd = TTF_OpenFont("Fonts/framd.ttf", 82);
	FRAMDCN = TTF_OpenFont("Fonts/FRAMDCN.ttf", 82);
	framdit = TTF_OpenFont("Fonts/framdit.ttf", 82);
	FREESCPT = TTF_OpenFont("Fonts/FREESCPT.ttf", 82);
	FRSCRIPT = TTF_OpenFont("Fonts/FRSCRIPT.ttf", 82);
	FTLTLT = TTF_OpenFont("Fonts/FTLTLT.ttf", 82);
	Gabriola = TTF_OpenFont("Fonts/Gabriola.ttf", 82);
	gadugi = TTF_OpenFont("Fonts/gadugi.ttf", 82);
	gadugib = TTF_OpenFont("Fonts/gadugib.ttf", 82);
	GARA = TTF_OpenFont("Fonts/GARA.ttf", 82);
	GARABD = TTF_OpenFont("Fonts/GARABD.ttf", 82);
	GARAIT = TTF_OpenFont("Fonts/GARAIT.ttf", 82);
	georgia = TTF_OpenFont("Fonts/georgia.ttf", 82);
	georgiab = TTF_OpenFont("Fonts/georgiab.ttf", 82);
	georgiai = TTF_OpenFont("Fonts/georgiai.ttf", 82);
	georgiaz = TTF_OpenFont("Fonts/georgiaz.ttf", 82);
	GIGI = TTF_OpenFont("Fonts/GIGI.ttf", 82);
	GIL_____ = TTF_OpenFont("Fonts/GIL_____.ttf", 82);
	GILB____ = TTF_OpenFont("Fonts/GILB____.ttf", 82);
	GILBI___ = TTF_OpenFont("Fonts/GILBI___.ttf", 82);
	GILC____ = TTF_OpenFont("Fonts/GILC____.ttf", 82);
	GILI____ = TTF_OpenFont("Fonts/GILI____.ttf", 82);
	GILLUBCD = TTF_OpenFont("Fonts/GILLUBCD.ttf", 82);
	GILSANUB = TTF_OpenFont("Fonts/GILSANUB.ttf", 82);
	GLECB = TTF_OpenFont("Fonts/GLECB.ttf", 82);
	GLSNECB = TTF_OpenFont("Fonts/GLSNECB.ttf", 82);
	GOTHIC = TTF_OpenFont("Fonts/GOTHIC.ttf", 82);
	GOTHICB = TTF_OpenFont("Fonts/GOTHICB.ttf", 82);
	GOTHICBI = TTF_OpenFont("Fonts/GOTHICBI.ttf", 82);
	GOTHICI = TTF_OpenFont("Fonts/GOTHICI.ttf", 82);
	GOUDOS = TTF_OpenFont("Fonts/GOUDOS.ttf", 82);
	GOUDOSB = TTF_OpenFont("Fonts/GOUDOSB.ttf", 82);
	GOUDOSI = TTF_OpenFont("Fonts/GOUDOSI.ttf", 82);
	GOUDYSTO = TTF_OpenFont("Fonts/GOUDYSTO.ttf", 82);
	HARLOWSI = TTF_OpenFont("Fonts/HARLOWSI.ttf", 82);
	HARNGTON = TTF_OpenFont("Fonts/HARNGTON.ttf", 82);
	HATTEN = TTF_OpenFont("Fonts/HATTEN.ttf", 82);
	holomdl2 = TTF_OpenFont("Fonts/holomdl2.ttf", 82);
	HPSimplified = TTF_OpenFont("Fonts/HPSimplified.ttf", 82);
	HPSimplified_BdIt = TTF_OpenFont("Fonts/HPSimplified_BdIt.ttf", 82);
	HPSimplified_It = TTF_OpenFont("Fonts/HPSimplified_It.ttf", 82);
	HPSimplified_Lt = TTF_OpenFont("Fonts/HPSimplified_Lt.ttf", 82);
	HPSimplified_LtIt = TTF_OpenFont("Fonts/HPSimplified_LtIt.ttf", 82);
	HPSimplified_Rg = TTF_OpenFont("Fonts/HPSimplified_Rg.ttf", 82);
	//
	hpsimplifiedjpan_light = TTF_OpenFont("Fonts/hpsimplifiedjpan_light.ttf", 82);
	//
	hpsimplifiedjpan_regular = TTF_OpenFont("Fonts/hpsimplifiedjpan_regular.ttf", 82);
	HTOWERT = TTF_OpenFont("Fonts/HTOWERT.ttf", 82);
	HTOWERTI = TTF_OpenFont("Fonts/HTOWERTI.ttf", 82);
	impact = TTF_OpenFont("Fonts/impact.ttf", 82);
	IMPRISHA = TTF_OpenFont("Fonts/IMPRISHA.ttf", 82);
	INFROMAN = TTF_OpenFont("Fonts/INFROMAN.ttf", 82);
	Inkfree = TTF_OpenFont("Fonts/Inkfree.ttf", 82);
	ITCBLKAD = TTF_OpenFont("Fonts/ITCBLKAD.ttf", 82);
	ITCEDSCR = TTF_OpenFont("Fonts/ITCEDSCR.ttf", 82);
	ITCKRIST = TTF_OpenFont("Fonts/ITCKRIST.ttf", 82);
	javatext = TTF_OpenFont("Fonts/javatext.ttf", 82);
	JOKERMAN = TTF_OpenFont("Fonts/JOKERMAN.ttf", 82);
	JUICE___ = TTF_OpenFont("Fonts/JUICE___.ttf", 82);
	KUNSTLER = TTF_OpenFont("Fonts/KUNSTLER.ttf", 82);
	l_10646 = TTF_OpenFont("Fonts/l_10646.ttf", 82);
	LATINWD = TTF_OpenFont("Fonts/LATINWD.ttf", 82);
	LBRITE = TTF_OpenFont("Fonts/LBRITE.ttf", 82);
	LBRITED = TTF_OpenFont("Fonts/LBRITED.ttf", 82);
	LBRITEDI = TTF_OpenFont("Fonts/LBRITEDI.ttf", 82);
	LBRITEI = TTF_OpenFont("Fonts/LBRITEI.ttf", 82);
	LCALLIG = TTF_OpenFont("Fonts/LCALLIG.ttf", 82);
	LFAX = TTF_OpenFont("Fonts/LFAX.ttf", 82);
	LFAXD = TTF_OpenFont("Fonts/LFAXD.ttf", 82);
	LFAXDI = TTF_OpenFont("Fonts/LFAXDI.ttf", 82);
	LFAXI = TTF_OpenFont("Fonts/LFAXI.ttf", 82);
	LHANDW = TTF_OpenFont("Fonts/LHANDW.ttf", 82);
	LSANS = TTF_OpenFont("Fonts/LSANS.ttf", 82);
	LSANSD = TTF_OpenFont("Fonts/LSANSD.ttf", 82);
	LSANSDI = TTF_OpenFont("Fonts/LSANSDI.ttf", 82);
	LSANSI = TTF_OpenFont("Fonts/LSANSI.ttf", 82);
	LTYPE = TTF_OpenFont("Fonts/LTYPE.ttf", 82);
	LTYPEB = TTF_OpenFont("Fonts/LTYPEB.ttf", 82);
	LTYPEBO = TTF_OpenFont("Fonts/LTYPEBO.ttf", 82);
	LTYPEO = TTF_OpenFont("Fonts/LTYPEO.ttf", 82);
	lucon = TTF_OpenFont("Fonts/lucon.ttf", 82);
	MAGNETOB = TTF_OpenFont("Fonts/MAGNETOB.ttf", 82);
	MAIAN = TTF_OpenFont("Fonts/MAIAN.ttf", 82);
	MATURASC = TTF_OpenFont("Fonts/MATURASC.ttf", 82);
	MISTRAL = TTF_OpenFont("Fonts/MISTRAL.ttf", 82);
	mmrtext = TTF_OpenFont("Fonts/mmrtext.ttf", 82);
	MOD20 = TTF_OpenFont("Fonts/MOD20.ttf", 82);
	MTCORSVA = TTF_OpenFont("Fonts/MTCORSVA.ttf", 82);
	NIAGENG = TTF_OpenFont("Fonts/NIAGENG.ttf", 82);
	NIAGSOL = TTF_OpenFont("Fonts/NIAGSOL.ttf", 82);
	OCRAEXT = TTF_OpenFont("Fonts/OCRAEXT.ttf", 82);
	OLDENGL = TTF_OpenFont("Fonts/OLDENGL.ttf", 82);
	ONYX = TTF_OpenFont("Fonts/ONYX.ttf", 82);
	pala = TTF_OpenFont("Fonts/pala.ttf", 82);
	palab = TTF_OpenFont("Fonts/palab.ttf", 82);
	palabi = TTF_OpenFont("Fonts/palabi.ttf", 82);
	palai = TTF_OpenFont("Fonts/palai.ttf", 82);
	PALSCRI = TTF_OpenFont("Fonts/PALSCRI.ttf", 82);
	PAPYRUS = TTF_OpenFont("Fonts/PAPYRUS.ttf", 82);
	PARCHM = TTF_OpenFont("Fonts/PARCHM.ttf", 82);
	PER_____ = TTF_OpenFont("Fonts/PER_____.ttf", 82);
	PERB____ = TTF_OpenFont("Fonts/PERB____.ttf", 82);
	PERBI___ = TTF_OpenFont("Fonts/PERBI___.ttf", 82);
	PERI____ = TTF_OpenFont("Fonts/PERI____.ttf", 82);
	PERTIBD = TTF_OpenFont("Fonts/PERTIBD.ttf", 82);
	PERTILI = TTF_OpenFont("Fonts/PERTILI.ttf", 82);
	PLAYBILL = TTF_OpenFont("Fonts/PLAYBILL.ttf", 82);
	POORICH = TTF_OpenFont("Fonts/POORICH.ttf", 82);
	PRISTINA = TTF_OpenFont("Fonts/PRISTINA.ttf", 82);
	RAGE = TTF_OpenFont("Fonts/RAGE.ttf", 82);
	RAVIE = TTF_OpenFont("Fonts/RAVIE.ttf", 82);
	REFSAN = TTF_OpenFont("Fonts/REFSAN.ttf", 82);
	REFSPCL = TTF_OpenFont("Fonts/REFSPCL.ttf", 82);
	ROCC____ = TTF_OpenFont("Fonts/ROCC____.ttf", 82);
	ROCCB___ = TTF_OpenFont("Fonts/ROCCB___.ttf", 82);
	ROCK = TTF_OpenFont("Fonts/ROCK.ttf", 82);
	ROCKB = TTF_OpenFont("Fonts/ROCKB.ttf", 82);
	ROCKBI = TTF_OpenFont("Fonts/ROCKBI.ttf", 82);
	ROCKEB = TTF_OpenFont("Fonts/ROCKEB.ttf", 82);
	ROCKI = TTF_OpenFont("Fonts/ROCKI.ttf", 82);
	SCHLBKB = TTF_OpenFont("Fonts/SCHLBKB.ttf", 82);
	SCHLBKBI = TTF_OpenFont("Fonts/SCHLBKBI.ttf", 82);
	SCHLBKI = TTF_OpenFont("Fonts/SCHLBKI.ttf", 82);
	SCRIPTBL = TTF_OpenFont("Fonts/SCRIPTBL.ttf", 82);
	segmdl2 = TTF_OpenFont("Fonts/segmdl2.ttf", 82);
	segoepr = TTF_OpenFont("Fonts/segoepr.ttf", 82);
	segoeprb = TTF_OpenFont("Fonts/segoeprb.ttf", 82);
	segoesc = TTF_OpenFont("Fonts/segoesc.ttf", 82);
	segoescb = TTF_OpenFont("Fonts/segoescb.ttf", 82);
	segoeui = TTF_OpenFont("Fonts/segoeui.ttf", 82);
	segoeuib = TTF_OpenFont("Fonts/segoeuib.ttf", 82);
	segoeuii = TTF_OpenFont("Fonts/segoeuii.ttf", 82);
	segoeuil = TTF_OpenFont("Fonts/segoeuil.ttf", 82);
	segoeuisl = TTF_OpenFont("Fonts/segoeuisl.ttf", 82);
	segoeuiz = TTF_OpenFont("Fonts/segoeuiz.ttf", 82);
	//
	SegoeWP_Black_0 = TTF_OpenFont("Fonts/SegoeWP_Black_0.ttf", 82);
	//
	SegoeWP_Bold_0 = TTF_OpenFont("Fonts/SegoeWP_Bold_0.ttf", 82);
	//
	SegoeWP_Light_0 = TTF_OpenFont("Fonts/SegoeWP_Light_0.ttf", 82);
	//
	SegoeWP_Semibold_0 = TTF_OpenFont("Fonts/SegoeWP_Semibold_0.ttf", 82);
	//
	SegoeWP_Semilight_0 = TTF_OpenFont("Fonts/SegoeWP_Semilight_0.ttf", 82);
	seguibl = TTF_OpenFont("Fonts/seguibl.ttf", 82);
	seguibli = TTF_OpenFont("Fonts/seguibli.ttf", 82);
	seguiemj = TTF_OpenFont("Fonts/seguiemj.ttf", 82);
	seguihis = TTF_OpenFont("Fonts/seguihis.ttf", 82);
	seguili = TTF_OpenFont("Fonts/seguili.ttf", 82);
	seguisb = TTF_OpenFont("Fonts/seguisb.ttf", 82);
	seguisbi = TTF_OpenFont("Fonts/seguisbi.ttf", 82);
	seguisli = TTF_OpenFont("Fonts/seguisli.ttf", 82);
	seguisym = TTF_OpenFont("Fonts/seguisym.ttf", 82);
	SHOWG = TTF_OpenFont("Fonts/SHOWG.ttf", 82);
	SNAP____ = TTF_OpenFont("Fonts/SNAP____.ttf", 82);
	STENCIL = TTF_OpenFont("Fonts/STENCIL.ttf", 82);
	sylfaen = TTF_OpenFont("Fonts/sylfaen.ttf", 82);
	symbol = TTF_OpenFont("Fonts/symbol.ttf", 82);
	tahoma = TTF_OpenFont("Fonts/tahoma.ttf", 82);
	tahomabd = TTF_OpenFont("Fonts/tahomabd.ttf", 82);
	TCB_____ = TTF_OpenFont("Fonts/TCB_____.ttf", 82);
	TCBI____ = TTF_OpenFont("Fonts/TCBI____.ttf", 82);
	TCCB____ = TTF_OpenFont("Fonts/TCCB____.ttf", 82);
	TCCEB = TTF_OpenFont("Fonts/TCCEB.ttf", 82);
	TCCM____ = TTF_OpenFont("Fonts/TCCM____.ttf", 82);
	TCM_____ = TTF_OpenFont("Fonts/TCM_____.ttf", 82);
	TCMI____ = TTF_OpenFont("Fonts/TCMI____.ttf", 82);
	TEMPSITC = TTF_OpenFont("Fonts/TEMPSITC.ttf", 82);
	times = TTF_OpenFont("Fonts/times.ttf", 82);
	timesbd = TTF_OpenFont("Fonts/timesbd.ttf", 82);
	timesbi = TTF_OpenFont("Fonts/timesbi.ttf", 82);
	timesi = TTF_OpenFont("Fonts/timesi.ttf", 82);
	trebuc = TTF_OpenFont("Fonts/trebuc.ttf", 82);
	trebucbd = TTF_OpenFont("Fonts/trebucbd.ttf", 82);
	trebucbi = TTF_OpenFont("Fonts/trebucbi.ttf", 82);
	trebucit = TTF_OpenFont("Fonts/trebucit.ttf", 82);
	verdana = TTF_OpenFont("Fonts/verdana.ttf", 82);
	verdanab = TTF_OpenFont("Fonts/verdanab.ttf", 82);
	verdanai = TTF_OpenFont("Fonts/verdanai.ttf", 82);
	verdanaz = TTF_OpenFont("Fonts/verdanaz.ttf", 82);
	VINERITC = TTF_OpenFont("Fonts/VINERITC.ttf", 82);
	VIVALDII = TTF_OpenFont("Fonts/VIVALDII.ttf", 82);
	VLADIMIR = TTF_OpenFont("Fonts/VLADIMIR.ttf", 82);
	webdings = TTF_OpenFont("Fonts/webdings.ttf", 82);
	wingding = TTF_OpenFont("Fonts/wingding.ttf", 82);
	WINGDNG2 = TTF_OpenFont("Fonts/WINGDNG2.ttf", 82);
	WINGDNG3 = TTF_OpenFont("Fonts/WINGDNG3.ttf", 82);

	Fonts.push_back(CalibriFont);
	Fonts.push_back(AGENCYB);
	Fonts.push_back(AGENCYR);
	Fonts.push_back(ALGER);
	Fonts.push_back(ANTQUAB);
	Fonts.push_back(ANTQUABI);
	Fonts.push_back(ANTQUAI);
	Fonts.push_back(arial);
	Fonts.push_back(arialbd);
	Fonts.push_back(arialbi);
	Fonts.push_back(ariali);
	Fonts.push_back(ARIALN);
	Fonts.push_back(ARIALNB);
	Fonts.push_back(ARIALNBI);
	Fonts.push_back(ARIALNI);
	Fonts.push_back(ariblk);
	Fonts.push_back(ARLRDBD);
	Fonts.push_back(bahnschrift);
	Fonts.push_back(BASKVILL);
	Fonts.push_back(BAUHS93);
	Fonts.push_back(BELL);
	Fonts.push_back(BELLB);
	Fonts.push_back(BELLI);
	Fonts.push_back(BERNHC);
	Fonts.push_back(BKANT);
	Fonts.push_back(BOD_B);
	Fonts.push_back(BOD_BI);
	Fonts.push_back(BOD_BLAI);
	Fonts.push_back(BOD_BLAR);
	Fonts.push_back(BOD_CB);
	Fonts.push_back(BOD_CBI);
	Fonts.push_back(BOD_CI);
	Fonts.push_back(BOD_CR);
	Fonts.push_back(BOD_I);
	Fonts.push_back(BOD_PSTC);
	Fonts.push_back(BOD_R);
	Fonts.push_back(BOOKOS);
	Fonts.push_back(BOOKOSB);
	Fonts.push_back(BOOKOSBI);
	Fonts.push_back(BOOKOSI);
	Fonts.push_back(BRADHITC);
	Fonts.push_back(BRITANIC);
	Fonts.push_back(BRLNSB);
	Fonts.push_back(BRLNSDB);
	Fonts.push_back(BRLNSR);
	Fonts.push_back(BROADW);
	Fonts.push_back(BRUSHSCI);
	Fonts.push_back(BSSYM7);
	Fonts.push_back(calibrib);
	Fonts.push_back(calibrii);
	Fonts.push_back(calibril);
	Fonts.push_back(calibrili);
	Fonts.push_back(calibriz);
	Fonts.push_back(CALIFB);
	Fonts.push_back(CALIFI);
	Fonts.push_back(CALIFR);
	Fonts.push_back(CALIST);
	Fonts.push_back(CALISTB);
	Fonts.push_back(CALISTBI);
	Fonts.push_back(CALISTI);
	Fonts.push_back(cambriab);
	Fonts.push_back(cambriai);
	Fonts.push_back(cambriaz);
	Fonts.push_back(Candara);
	Fonts.push_back(Candarab);
	Fonts.push_back(Candarai);
	Fonts.push_back(Candaral);
	Fonts.push_back(Candarali);
	Fonts.push_back(Candaraz);
	Fonts.push_back(CASTELAR);
	Fonts.push_back(CENSCBK);
	Fonts.push_back(CENTAUR);
	Fonts.push_back(CENTURY);
	Fonts.push_back(CHILLER);
	Fonts.push_back(COLONNA);
	Fonts.push_back(comic);
	Fonts.push_back(comicbd);
	Fonts.push_back(comici);
	Fonts.push_back(comicz);
	Fonts.push_back(consola);
	Fonts.push_back(consolab);
	Fonts.push_back(consolai);
	Fonts.push_back(consolaz);
	Fonts.push_back(constan);
	Fonts.push_back(constanb);
	Fonts.push_back(constani);
	Fonts.push_back(constanz);
	Fonts.push_back(COOPBL);
	Fonts.push_back(COPRGTB);
	Fonts.push_back(COPRGTL);
	Fonts.push_back(corbel);
	Fonts.push_back(corbelb);
	Fonts.push_back(corbeli);
	Fonts.push_back(corbell);
	Fonts.push_back(corbelli);
	Fonts.push_back(corbelz);
	Fonts.push_back(cour);
	Fonts.push_back(courbd);
	Fonts.push_back(courbi);
	Fonts.push_back(couri);
	Fonts.push_back(CURLZ___);
	Fonts.push_back(ebrima);
	Fonts.push_back(ebrimabd);
	Fonts.push_back(ELEPHNT);
	Fonts.push_back(ELEPHNTI);
	Fonts.push_back(ENGR);
	Fonts.push_back(ERASBD);
	Fonts.push_back(ERASDEMI);
	Fonts.push_back(ERASLGHT);
	Fonts.push_back(ERASMD);
	Fonts.push_back(FELIXTI);
	Fonts.push_back(FORTE);
	Fonts.push_back(FRABK);
	Fonts.push_back(FRABKIT);
	Fonts.push_back(FRADM);
	Fonts.push_back(FRADMCN);
	Fonts.push_back(FRADMIT);
	Fonts.push_back(FRAHV);
	Fonts.push_back(FRAHVIT);
	Fonts.push_back(framd);
	Fonts.push_back(FRAMDCN);
	Fonts.push_back(FRADMCN);
	Fonts.push_back(framdit);
	Fonts.push_back(FREESCPT);
	Fonts.push_back(FRSCRIPT);
	Fonts.push_back(FTLTLT);
	Fonts.push_back(Gabriola);
	Fonts.push_back(gadugi);
	Fonts.push_back(gadugib);
	Fonts.push_back(GARA);
	Fonts.push_back(GARABD);
	Fonts.push_back(GARAIT);
	Fonts.push_back(georgia);
	Fonts.push_back(georgiab);
	Fonts.push_back(georgiai);
	Fonts.push_back(georgiaz);
	Fonts.push_back(GIGI);
	Fonts.push_back(GIL_____);
	Fonts.push_back(GILB____);
	Fonts.push_back(GILBI___);
	Fonts.push_back(GILC____);
	Fonts.push_back(GILI____);
	Fonts.push_back(GILLUBCD);
	Fonts.push_back(GILSANUB);
	Fonts.push_back(GLECB);
	Fonts.push_back(GLSNECB);
	Fonts.push_back(GOTHIC);
	Fonts.push_back(GOTHICB);
	Fonts.push_back(GOTHICBI);
	Fonts.push_back(GOTHICI);
	Fonts.push_back(GOUDOS);
	Fonts.push_back(GOUDOSB);
	Fonts.push_back(GOUDOSI);
	Fonts.push_back(GOUDYSTO);
	Fonts.push_back(HARLOWSI);
	Fonts.push_back(HARNGTON);
	Fonts.push_back(HATTEN);
	Fonts.push_back(holomdl2);
	Fonts.push_back(HPSimplified);
	Fonts.push_back(HPSimplified_BdIt);
	Fonts.push_back(HPSimplified_It);
	Fonts.push_back(HPSimplified_Lt);
	Fonts.push_back(HPSimplified_LtIt);
	Fonts.push_back(HPSimplified_Rg);
	//
	Fonts.push_back(hpsimplifiedjpan_light);
	//
	Fonts.push_back(hpsimplifiedjpan_regular);
	Fonts.push_back(HTOWERT);
	Fonts.push_back(HTOWERTI);
	Fonts.push_back(impact);
	Fonts.push_back(IMPRISHA);
	Fonts.push_back(INFROMAN);
	Fonts.push_back(Inkfree);
	Fonts.push_back(ITCBLKAD);
	Fonts.push_back(ITCEDSCR);
	Fonts.push_back(ITCKRIST);
	Fonts.push_back(javatext);
	Fonts.push_back(JOKERMAN);
	Fonts.push_back(JUICE___);
	Fonts.push_back(KUNSTLER);
	Fonts.push_back(l_10646);
	Fonts.push_back(LATINWD);
	Fonts.push_back(LBRITE);
	Fonts.push_back(LBRITED);
	Fonts.push_back(LBRITEDI);
	Fonts.push_back(LBRITEI);
	Fonts.push_back(LCALLIG);
	Fonts.push_back(LFAX);
	Fonts.push_back(LFAXD);
	Fonts.push_back(LFAXDI);
	Fonts.push_back(LFAXI);
	Fonts.push_back(LHANDW);
	Fonts.push_back(LSANS);
	Fonts.push_back(LSANSD);
	Fonts.push_back(LSANSDI);
	Fonts.push_back(LSANSI);
	Fonts.push_back(LTYPE);
	Fonts.push_back(LTYPEB);
	Fonts.push_back(LTYPEBO);
	Fonts.push_back(LTYPEO);
	Fonts.push_back(lucon);
	Fonts.push_back(MAGNETOB);
	Fonts.push_back(MAIAN);
	Fonts.push_back(MATURASC);
	Fonts.push_back(MISTRAL);
	Fonts.push_back(mmrtext);
	Fonts.push_back(MOD20);
	Fonts.push_back(MTCORSVA);
	Fonts.push_back(NIAGENG);
	Fonts.push_back(NIAGSOL);
	Fonts.push_back(OCRAEXT);
	Fonts.push_back(OLDENGL);
	Fonts.push_back(ONYX);
	Fonts.push_back(pala);
	Fonts.push_back(palab);
	Fonts.push_back(palabi);
	Fonts.push_back(palai);
	Fonts.push_back(PALSCRI);
	Fonts.push_back(PAPYRUS);
	Fonts.push_back(PARCHM);
	Fonts.push_back(PER_____);
	Fonts.push_back(PERB____);
	Fonts.push_back(PERBI___);
	Fonts.push_back(PERI____);
	Fonts.push_back(PERTIBD);
	Fonts.push_back(PERTILI);
	Fonts.push_back(PLAYBILL);
	Fonts.push_back(POORICH);
	Fonts.push_back(PRISTINA);
	Fonts.push_back(RAGE);
	Fonts.push_back(RAVIE);
	Fonts.push_back(REFSAN);
	Fonts.push_back(REFSPCL);
	Fonts.push_back(ROCC____);
	Fonts.push_back(ROCCB___);
	Fonts.push_back(ROCK);
	Fonts.push_back(ROCKB);
	Fonts.push_back(ROCKBI);
	Fonts.push_back(ROCKEB);
	Fonts.push_back(ROCKI);
	Fonts.push_back(SCHLBKB);
	Fonts.push_back(SCHLBKBI);
	Fonts.push_back(SCHLBKI);
	Fonts.push_back(SCRIPTBL);
	Fonts.push_back(segmdl2);
	Fonts.push_back(segoepr);
	Fonts.push_back(segoeprb);
	Fonts.push_back(segoesc);
	Fonts.push_back(segoescb);
	Fonts.push_back(segoeui);
	Fonts.push_back(segoeuib);
	Fonts.push_back(segoeuii);
	Fonts.push_back(segoeuil);
	Fonts.push_back(segoeuisl);
	Fonts.push_back(segoeuiz);
	//
	Fonts.push_back(SegoeWP_Black_0);
	//
	Fonts.push_back(SegoeWP_Bold_0);
	//
	Fonts.push_back(SegoeWP_Light_0);
	//
	Fonts.push_back(SegoeWP_Semibold_0);
	//
	Fonts.push_back(seguibl);
	Fonts.push_back(seguibli);
	Fonts.push_back(seguiemj);
	Fonts.push_back(seguihis);
	Fonts.push_back(seguili);
	Fonts.push_back(seguisb);
	Fonts.push_back(seguisbi);
	Fonts.push_back(seguisli);
	Fonts.push_back(seguisym);
	Fonts.push_back(SHOWG);
	Fonts.push_back(SNAP____);
	Fonts.push_back(STENCIL);
	Fonts.push_back(sylfaen);
	Fonts.push_back(symbol);
	Fonts.push_back(tahoma);
	Fonts.push_back(tahomabd);
	Fonts.push_back(TCB_____);
	Fonts.push_back(TCBI____);
	Fonts.push_back(TCCB____);
	Fonts.push_back(TCCEB);
	Fonts.push_back(TCCM____);
	Fonts.push_back(TCM_____);
	Fonts.push_back(TCMI____);
	Fonts.push_back(TEMPSITC);
	Fonts.push_back(times);
	Fonts.push_back(timesbd);
	Fonts.push_back(timesbi);
	Fonts.push_back(timesi);
	Fonts.push_back(trebuc);
	Fonts.push_back(trebucbd);
	Fonts.push_back(trebucbi);
	Fonts.push_back(trebucit);
	Fonts.push_back(verdana);
	Fonts.push_back(verdanab);
	Fonts.push_back(verdanai);
	Fonts.push_back(verdanaz);
	Fonts.push_back(VINERITC);
	Fonts.push_back(VIVALDII);
	Fonts.push_back(VLADIMIR);
	Fonts.push_back(webdings);
	Fonts.push_back(wingding);
	Fonts.push_back(WINGDNG2);
	Fonts.push_back(WINGDNG3);

	for (int i = 0; i < Fonts.size(); i++)
	{
		if (Fonts[i] == nullptr)
		{
			std::string LogMessage = "Couldn't Load All The Fonts. " + std::string(SDL_GetError());

			ErrorReporter::LogMessage("Error", LogMessage.c_str());

			return;
		}
	}
}

SDL_Texture* TextTexture = nullptr;
SDL_Surface* TextSurface = nullptr;

SDL_Texture* RenderText::CreateNewTexture(const char* Text, SDL_Rect TextRect, const char* Font, SDL_Colour textColour)
{
	SDL_DestroyTexture(TextTexture);

	TextSurface = TTF_RenderText_Blended_Wrapped(CalibriFont, Text, textColour, TextRect.w);

	TextTexture = SDL_CreateTextureFromSurface(Init::Renderer, TextSurface);

	SDL_QueryTexture(TextTexture, nullptr, nullptr, &TextRect.w, &TextRect.h);
	SDL_FreeSurface(TextSurface);

	return TextTexture;
}

void RenderText::Clean()
{
	TTF_Quit();
}
